$axure.loadCurrentPage({
  "url":"提供者认证.html",
  "generationDate":new Date(1488181345363.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9376f1060c1144c49925a4a0e71c086b",
    "type":"Axure:Page",
    "name":"提供者认证",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b3618122e5244168a636e08c83538fb4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":400.5,
              "y":149},
            "size":{
              "width":569,
              "height":361}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0615a52dfd7429fa0e78b4a794c944e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400.5,
                  "y":149},
                "size":{
                  "width":569,
                  "height":361}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提供者认证/u0.png"}},
{
          "id":"a5127e91487c4d0cb41283742b802b22",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6e03aba969a64804a7fa4490ab766812"},
{
          "id":"2af530a93d2d4a4fb0734d2abf987742",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":570,
              "y":450},
            "size":{
              "width":150,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 业务线管理-无",
                      "target":{
                        "targetType":"page",
                        "url":"业务线管理-无.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "6e03aba969a64804a7fa4490ab766812":{
      "packageId":"6e03aba969a64804a7fa4490ab766812",
      "type":"Axure:Master",
      "name":"banner",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a379bbcedb33484ebee107fd9c00378e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1370,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"623ed66a746d41b3a92930eccc112eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1370,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u1.png"}},
{
            "id":"7e02905f180d444e82bf7a5e5f714ed2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":146,
                "y":40},
              "size":{
                "width":114,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23469a3e4ec040068e7550ebfc87d3fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":146,
                    "y":40},
                  "size":{
                    "width":114,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b922b24f0c8c43d79cb58b86621900a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":25},
              "size":{
                "width":100,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97728730fc9e442e987885d0bedd7b6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":25},
                  "size":{
                    "width":100,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u5.png"}},
{
            "id":"0980d651269a4ee0996ac0911a37f74d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":360,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0890f7341e6a49ddb31eb81acdbadf59",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":360,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-登陆后",
                        "target":{
                          "targetType":"page",
                          "url":"首页-登陆后.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"65cb50f858734024be55b79cf7647867",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":520,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"950e973e89a14b04b6aeb8769318250d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":520,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c5c2818163684e16951f2f96bb2e461e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f5a0cb72b6d94ce992936281e7e57efa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c80392740b724ca4a02d640db27ef42d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1176,
                "y":34},
              "size":{
                "width":94,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"574479846c4b4024bf9f32b14cbbf5ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1176,
                    "y":34},
                  "size":{
                    "width":94,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心-基本信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心-基本信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a60fa91d82174ea3afaf66f60115cb57",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1170,
                "y":50},
              "size":{
                "width":120,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"604f3c8191be4df9a58c3e7fb2d464e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1170,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 业务线管理-未认证",
                        "target":{
                          "targetType":"page",
                          "url":"业务线管理-未认证.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u15.png"}}]}}},
  "objectPaths":{
    "b3618122e5244168a636e08c83538fb4":{
      "scriptId":"u0"},
    "b0615a52dfd7429fa0e78b4a794c944e":{
      "scriptId":"u1"},
    "a5127e91487c4d0cb41283742b802b22":{
      "scriptId":"u2",
      "a379bbcedb33484ebee107fd9c00378e":{
        "scriptId":"u3"},
      "623ed66a746d41b3a92930eccc112eeb":{
        "scriptId":"u4"},
      "7e02905f180d444e82bf7a5e5f714ed2":{
        "scriptId":"u5"},
      "23469a3e4ec040068e7550ebfc87d3fd":{
        "scriptId":"u6"},
      "b922b24f0c8c43d79cb58b86621900a2":{
        "scriptId":"u7"},
      "97728730fc9e442e987885d0bedd7b6d":{
        "scriptId":"u8"},
      "0980d651269a4ee0996ac0911a37f74d":{
        "scriptId":"u9"},
      "0890f7341e6a49ddb31eb81acdbadf59":{
        "scriptId":"u10"},
      "65cb50f858734024be55b79cf7647867":{
        "scriptId":"u11"},
      "950e973e89a14b04b6aeb8769318250d":{
        "scriptId":"u12"},
      "c5c2818163684e16951f2f96bb2e461e":{
        "scriptId":"u13"},
      "f5a0cb72b6d94ce992936281e7e57efa":{
        "scriptId":"u14"},
      "c80392740b724ca4a02d640db27ef42d":{
        "scriptId":"u15"},
      "574479846c4b4024bf9f32b14cbbf5ea":{
        "scriptId":"u16"},
      "a60fa91d82174ea3afaf66f60115cb57":{
        "scriptId":"u17"},
      "604f3c8191be4df9a58c3e7fb2d464e7":{
        "scriptId":"u18"}},
    "2af530a93d2d4a4fb0734d2abf987742":{
      "scriptId":"u19"}}});