$axure.loadCurrentPage({
  "url":"功能分组.html",
  "generationDate":new Date(1488533172552.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c55502e6832741b18e8295a55b824d73",
    "type":"Axure:Page",
    "name":"功能分组",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"185d02fcb55449e48a5f31f326639a18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":90},
            "size":{
              "width":626,
              "height":224}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ec7d4c549e7412ba389dd2f47006495",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":90},
                "size":{
                  "width":626,
                  "height":224}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a397a7efd56b4f8f8cbb77db9d6abc61",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":260},
            "size":{
              "width":662,
              "height":186}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9036f6e7acfb4186813619e5fcad4af4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":44,
                  "y":0},
                "size":{
                  "width":225,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c42f10415162425cbaec42c665dc72bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":44,
                      "y":0},
                    "size":{
                      "width":225,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u5.png"}},
{
              "id":"06364f38d0884ed6a53908854cef14d8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":36},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c4b2dca392e4b469b9ae3ae8b8c85e1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":44,
                      "y":36},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 接口信息",
                          "target":{
                            "targetType":"page",
                            "url":"接口信息.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/功能分组/u15.png"}},
{
              "id":"9d75bc7481384f778e81a15bf15d775a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":66},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7ae4cbe58ca4be4b21fc383c2090ea8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":44,
                      "y":66},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u15.png"}},
{
              "id":"9d5d0f20ce694151a4b76066bd1a5e09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":44,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43ebcde40cd04372bed034fb5e029971",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":44,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u3.png"}},
{
              "id":"48b9bf39d30d43cdad126939313520f8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":44,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7b0b0c1ffb244e88b67692f453c7d81d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":44,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u13.png"}},
{
              "id":"2423207004804b6faca0f8f5401bb77c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":44,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c959711c8bd4f709b24fc248517aad5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":44,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u13.png"}},
{
              "id":"1d7bf48a56c74364adf75f1865723b3c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":44,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9356f55e9de04bb6859b1980229c6f8f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":96},
                    "size":{
                      "width":44,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u13.png"}},
{
              "id":"fc0df728252f4a3fb57643077b10a20f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":96},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa4e417f60d74117af35437332999af6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":44,
                      "y":96},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u15.png"}},
{
              "id":"a5e5f963bf9146fbbf60f181ad4a90af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":156},
                "size":{
                  "width":44,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a80e9e4f1c1a41829c341520f8642ace",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":156},
                    "size":{
                      "width":44,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u53.png"}},
{
              "id":"705dbe8f5f47491d933ec73d31a0b7c0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":156},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fcc4a761be4e4bc8a18fbd90d4a29d89",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":44,
                      "y":156},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u55.png"}},
{
              "id":"3bf568a767cf444290530d9d960b1a13",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":126},
                "size":{
                  "width":44,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ccd60386a96a401182c36ea8c6811207",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":126},
                    "size":{
                      "width":44,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u13.png"}},
{
              "id":"8da9cc856d2d4a67b39afc720ff254d4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":126},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a09b1830fa024766a26dbcd396241925",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":44,
                      "y":126},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u15.png"}},
{
              "id":"f1775491fe564d6fa1ae8807439a551f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":269,
                  "y":0},
                "size":{
                  "width":176,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2fb02d1cb68430b9d5de6d568b120d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":269,
                      "y":0},
                    "size":{
                      "width":176,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u7.png"}},
{
              "id":"a07e8995b2294eb3941146387300b4c9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":269,
                  "y":36},
                "size":{
                  "width":176,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"046a99169e9142a88ce280485ea7d2ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":269,
                      "y":36},
                    "size":{
                      "width":176,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u17.png"}},
{
              "id":"79a91d6fc77e4c38abebded8fb239fe8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":269,
                  "y":66},
                "size":{
                  "width":176,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18e30bb6e70b4e73a19fc1bb8580bbb5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":269,
                      "y":66},
                    "size":{
                      "width":176,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u17.png"}},
{
              "id":"0a7d950868e54310a3c640954fa0e65f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":269,
                  "y":96},
                "size":{
                  "width":176,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"48dbd2a2ad8440bb8d5d07500c72df2c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":269,
                      "y":96},
                    "size":{
                      "width":176,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u17.png"}},
{
              "id":"fc54795002df4ad99443520b025f2516",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":269,
                  "y":126},
                "size":{
                  "width":176,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abb216c67e0740ff9c09edb40902e14d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":269,
                      "y":126},
                    "size":{
                      "width":176,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u17.png"}},
{
              "id":"4048de3f9ed449809516f3b79bdbf1e4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":269,
                  "y":156},
                "size":{
                  "width":176,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dbd4c3b756894a13b3566d885051d619",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":269,
                      "y":156},
                    "size":{
                      "width":176,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u57.png"}},
{
              "id":"9c357aeb6f074762ae52ee9d481fd0ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":445,
                  "y":0},
                "size":{
                  "width":123,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f9676e6e9bbd45b3b28481205b98ce45",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":445,
                      "y":0},
                    "size":{
                      "width":123,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u9.png"}},
{
              "id":"ccfb2512edc44a88a0cc8de01baf5390",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":36},
                "size":{
                  "width":123,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9deecb37258747d39433530594d79eed",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":445,
                      "y":36},
                    "size":{
                      "width":123,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u19.png"}},
{
              "id":"5b4a7c7be3824ae3b013556cbb7693c6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":66},
                "size":{
                  "width":123,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5b304aae3d64fbda4c44ff5ff33aff0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":445,
                      "y":66},
                    "size":{
                      "width":123,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u19.png"}},
{
              "id":"c88334e56d874d0f98e7cad3b6de610a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":96},
                "size":{
                  "width":123,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d57a78bca30543ef94c641363c99f95c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":445,
                      "y":96},
                    "size":{
                      "width":123,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u19.png"}},
{
              "id":"32a4495a0eae4a349002eb4407f29e34",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":126},
                "size":{
                  "width":123,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"20ef529954db4eaa910ede74c0ca1fa0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":445,
                      "y":126},
                    "size":{
                      "width":123,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u19.png"}},
{
              "id":"3831d453f094480b91df47473f75af8f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":156},
                "size":{
                  "width":123,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a130278126647b295ac5027bb01b16c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "location":{
                      "x":445,
                      "y":156},
                    "size":{
                      "width":123,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u59.png"}},
{
              "id":"948e5c370f214296aed10f0e1c5741a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":568,
                  "y":0},
                "size":{
                  "width":94,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41ef7bd82c704e6bbbe3de22733b4c00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":568,
                      "y":0},
                    "size":{
                      "width":94,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u11.png"}},
{
              "id":"aa5b630b40174a0e91fb7c4d9eb9a4fc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":568,
                  "y":36},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8e108ab7c8043ebb6567bf3c988573e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":568,
                      "y":36},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u21.png"}},
{
              "id":"a2061186d3bc4454bb0ad7a6763df649",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":568,
                  "y":66},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e309d2a71d2c4eb1b63509e7ef0e635b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":568,
                      "y":66},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u21.png"}},
{
              "id":"c37387a5e9a44f7d8b2785188a38f04c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":568,
                  "y":96},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dba1c3875444a7c93aead318700e684",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":568,
                      "y":96},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u21.png"}},
{
              "id":"38456c28861f4ad6b78eb82301a03598",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":568,
                  "y":126},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1839b9cbd5d64e0e8b1d319613f42889",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":568,
                      "y":126},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u21.png"}},
{
              "id":"abe5261fd8e24316bfa2cb3ae0ea21ca",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":568,
                  "y":156},
                "size":{
                  "width":94,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa36b2a18dbc4d2e9f2b03a52e345ef6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":568,
                      "y":156},
                    "size":{
                      "width":94,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u61.png"}}]},
{
          "id":"0b3bcfe8b06d4a71bbd984e2e6271864",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":908,
              "y":604},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6c7e71ac1594cbb9309a03450738ece",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":908,
                  "y":604},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1503317fa0e4e8faf500b2a6e9e8d6f",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"7a02efa0d5604338a3be75f38bcf2b86"},
{
          "id":"49617adce23a41dcaadbe1c587a59822",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1028,
              "y":292},
            "size":{
              "width":132,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e9c65d2b55349a7999cd5c7ea740f21",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1028,
                  "y":292},
                "size":{
                  "width":132,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f642e057fe9d460082f8f5b7b7973a55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":499},
            "size":{
              "width":340,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d5e057713de409ab4173d31beee73b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":499},
                "size":{
                  "width":340,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u82.png"}},
{
          "id":"35736b9ce89a4b64a552c49ffee87284",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":480},
            "size":{
              "width":340,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b95dfd2a6b8a476f8f9fd8f164a21fa1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":480},
                "size":{
                  "width":340,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u84.png"}},
{
          "id":"9fb9b165969a40f1b5335037bca1030b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":540},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f074510dd643404f8c05ed9f03e3f00e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":540},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"93ef014f02be4ce782473bf61f5fb3b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":444,
              "y":531},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8749611bd4fe47e2bf15a14c5e8684d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":444,
                  "y":531},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u88.png"}},
{
          "id":"85fbf11d2210454196256b440abedf26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":539,
              "y":531},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c5b38c05eed408189538162dd791de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":539,
                  "y":531},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u88.png"}},
{
          "id":"638ab710e6a84c059ade0f78ed81d291",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":368,
              "y":592},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b7ba806ea98403aa24e304dc6dd9912",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":368,
                  "y":592},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a91c65dc8de5407e9b9bf264e56992c0",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":434,
              "y":588},
            "size":{
              "width":220,
              "height":62}},
          "adaptiveStyles":{
}},
{
          "id":"3ddf9158f84d414cacfa4340786b0575",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":680},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fa75534821a24cd1883bf75185675041",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":539,
              "y":680},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e39d6b2dd3374c08a538acda43098942",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":744,
              "y":499},
            "size":{
              "width":340,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79bf24248724262bcda69cc73a1a4c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":744,
                  "y":499},
                "size":{
                  "width":340,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u82.png"}},
{
          "id":"cb73a578590b470c90f2a009c8764271",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":744,
              "y":480},
            "size":{
              "width":340,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eac330afda424d45ae8a5246ab177e1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":744,
                  "y":480},
                "size":{
                  "width":340,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u84.png"}},
{
          "id":"20cc722e1be94280a86d687419575d99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":768,
              "y":540},
            "size":{
              "width":246,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98de66fbf6da4f689943a0e0976ee3c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":768,
                  "y":540},
                "size":{
                  "width":246,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18297e112ebb4d2f80cb7ff1bd1c0818",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":864,
              "y":629},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"976f5b84e7444c5cbeaa16a9b642066b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":140,
              "y":117},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1073edd14c14360b5d6ca84ed961c25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":140,
                  "y":117},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 API接口审核",
                      "target":{
                        "targetType":"page",
                        "url":"api接口审核.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/开发者认证审核/u19.png"}},
{
          "id":"fc645e9df49b4f6599fa080153a8c496",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":334,
              "y":80},
            "size":{
              "width":56,
              "height":32}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 业务线信息",
                      "target":{
                        "targetType":"page",
                        "url":"业务线信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "7a02efa0d5604338a3be75f38bcf2b86":{
      "packageId":"7a02efa0d5604338a3be75f38bcf2b86",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"03bd36ac64d041918c6dc3aa6374751a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df66acca03bf499aa135bbcb6227b967",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"6b692c7b87a3402b9ce9a61959969a10",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0099FF,
                "opacity":1},
              "location":{
                "x":59,
                "y":18},
              "size":{
                "width":241,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c6cdd631e4d43428f7d756760855ef4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0099FF,
                    "opacity":1},
                  "location":{
                    "x":59,
                    "y":18},
                  "size":{
                    "width":241,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ff8b4a4f418f41888cc0cac89e0b6cc6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":59},
              "size":{
                "width":200,
                "height":421}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"95d3026929da487595c46ec0c6ac3c87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":59},
                  "size":{
                    "width":200,
                    "height":421}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u5.png"}},
{
            "id":"7afee1299b2b48a8a6be957ef89fe2af",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":59},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc8fa126bf8e4cc6a842e757b7b28f3f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":59},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API提供者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"api提供者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"b796130b619e4ad2b19a50e713cbbd40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":88},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b0b3db928fd4bdc8935f7e7b7748902",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":88},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 开发者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"开发者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"ef5b7a53388f4425b08610aa93a79189",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":175},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d9fbdea8ac94145a0e1dac4db9bfff5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":175},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 应用上线审核",
                        "target":{
                          "targetType":"page",
                          "url":"应用上线审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"a13a6ce77356497b9dcac880c9acd548",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":117},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4416e82b29c84e7cb040527f4c8a5b03",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":117},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API接口审核",
                        "target":{
                          "targetType":"page",
                          "url":"api接口审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"01bcdd63c23f4cdd8d8a524437ac1102",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":146},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82d50f80e0ba46fc820d9a4ca86db1f1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":146},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 接入指南审核",
                        "target":{
                          "targetType":"page",
                          "url":"接入指南审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"eabd7026a24944e1a21cd8e4f0df4689",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":204},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7cd7f6c343744aaf975767f39e9ee417",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":204},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 申请功能分组申请",
                        "target":{
                          "targetType":"page",
                          "url":"申请功能分组申请.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}}]}}},
  "objectPaths":{
    "185d02fcb55449e48a5f31f326639a18":{
      "scriptId":"u0"},
    "7ec7d4c549e7412ba389dd2f47006495":{
      "scriptId":"u1"},
    "a397a7efd56b4f8f8cbb77db9d6abc61":{
      "scriptId":"u2"},
    "9d5d0f20ce694151a4b76066bd1a5e09":{
      "scriptId":"u3"},
    "43ebcde40cd04372bed034fb5e029971":{
      "scriptId":"u4"},
    "9036f6e7acfb4186813619e5fcad4af4":{
      "scriptId":"u5"},
    "c42f10415162425cbaec42c665dc72bd":{
      "scriptId":"u6"},
    "f1775491fe564d6fa1ae8807439a551f":{
      "scriptId":"u7"},
    "c2fb02d1cb68430b9d5de6d568b120d2":{
      "scriptId":"u8"},
    "9c357aeb6f074762ae52ee9d481fd0ff":{
      "scriptId":"u9"},
    "f9676e6e9bbd45b3b28481205b98ce45":{
      "scriptId":"u10"},
    "948e5c370f214296aed10f0e1c5741a8":{
      "scriptId":"u11"},
    "41ef7bd82c704e6bbbe3de22733b4c00":{
      "scriptId":"u12"},
    "48b9bf39d30d43cdad126939313520f8":{
      "scriptId":"u13"},
    "7b0b0c1ffb244e88b67692f453c7d81d":{
      "scriptId":"u14"},
    "06364f38d0884ed6a53908854cef14d8":{
      "scriptId":"u15"},
    "2c4b2dca392e4b469b9ae3ae8b8c85e1":{
      "scriptId":"u16"},
    "a07e8995b2294eb3941146387300b4c9":{
      "scriptId":"u17"},
    "046a99169e9142a88ce280485ea7d2ce":{
      "scriptId":"u18"},
    "ccfb2512edc44a88a0cc8de01baf5390":{
      "scriptId":"u19"},
    "9deecb37258747d39433530594d79eed":{
      "scriptId":"u20"},
    "aa5b630b40174a0e91fb7c4d9eb9a4fc":{
      "scriptId":"u21"},
    "f8e108ab7c8043ebb6567bf3c988573e":{
      "scriptId":"u22"},
    "2423207004804b6faca0f8f5401bb77c":{
      "scriptId":"u23"},
    "5c959711c8bd4f709b24fc248517aad5":{
      "scriptId":"u24"},
    "9d75bc7481384f778e81a15bf15d775a":{
      "scriptId":"u25"},
    "d7ae4cbe58ca4be4b21fc383c2090ea8":{
      "scriptId":"u26"},
    "79a91d6fc77e4c38abebded8fb239fe8":{
      "scriptId":"u27"},
    "18e30bb6e70b4e73a19fc1bb8580bbb5":{
      "scriptId":"u28"},
    "5b4a7c7be3824ae3b013556cbb7693c6":{
      "scriptId":"u29"},
    "a5b304aae3d64fbda4c44ff5ff33aff0":{
      "scriptId":"u30"},
    "a2061186d3bc4454bb0ad7a6763df649":{
      "scriptId":"u31"},
    "e309d2a71d2c4eb1b63509e7ef0e635b":{
      "scriptId":"u32"},
    "1d7bf48a56c74364adf75f1865723b3c":{
      "scriptId":"u33"},
    "9356f55e9de04bb6859b1980229c6f8f":{
      "scriptId":"u34"},
    "fc0df728252f4a3fb57643077b10a20f":{
      "scriptId":"u35"},
    "aa4e417f60d74117af35437332999af6":{
      "scriptId":"u36"},
    "0a7d950868e54310a3c640954fa0e65f":{
      "scriptId":"u37"},
    "48dbd2a2ad8440bb8d5d07500c72df2c":{
      "scriptId":"u38"},
    "c88334e56d874d0f98e7cad3b6de610a":{
      "scriptId":"u39"},
    "d57a78bca30543ef94c641363c99f95c":{
      "scriptId":"u40"},
    "c37387a5e9a44f7d8b2785188a38f04c":{
      "scriptId":"u41"},
    "5dba1c3875444a7c93aead318700e684":{
      "scriptId":"u42"},
    "3bf568a767cf444290530d9d960b1a13":{
      "scriptId":"u43"},
    "ccd60386a96a401182c36ea8c6811207":{
      "scriptId":"u44"},
    "8da9cc856d2d4a67b39afc720ff254d4":{
      "scriptId":"u45"},
    "a09b1830fa024766a26dbcd396241925":{
      "scriptId":"u46"},
    "fc54795002df4ad99443520b025f2516":{
      "scriptId":"u47"},
    "abb216c67e0740ff9c09edb40902e14d":{
      "scriptId":"u48"},
    "32a4495a0eae4a349002eb4407f29e34":{
      "scriptId":"u49"},
    "20ef529954db4eaa910ede74c0ca1fa0":{
      "scriptId":"u50"},
    "38456c28861f4ad6b78eb82301a03598":{
      "scriptId":"u51"},
    "1839b9cbd5d64e0e8b1d319613f42889":{
      "scriptId":"u52"},
    "a5e5f963bf9146fbbf60f181ad4a90af":{
      "scriptId":"u53"},
    "a80e9e4f1c1a41829c341520f8642ace":{
      "scriptId":"u54"},
    "705dbe8f5f47491d933ec73d31a0b7c0":{
      "scriptId":"u55"},
    "fcc4a761be4e4bc8a18fbd90d4a29d89":{
      "scriptId":"u56"},
    "4048de3f9ed449809516f3b79bdbf1e4":{
      "scriptId":"u57"},
    "dbd4c3b756894a13b3566d885051d619":{
      "scriptId":"u58"},
    "3831d453f094480b91df47473f75af8f":{
      "scriptId":"u59"},
    "4a130278126647b295ac5027bb01b16c":{
      "scriptId":"u60"},
    "abe5261fd8e24316bfa2cb3ae0ea21ca":{
      "scriptId":"u61"},
    "aa36b2a18dbc4d2e9f2b03a52e345ef6":{
      "scriptId":"u62"},
    "0b3bcfe8b06d4a71bbd984e2e6271864":{
      "scriptId":"u63"},
    "f6c7e71ac1594cbb9309a03450738ece":{
      "scriptId":"u64"},
    "a1503317fa0e4e8faf500b2a6e9e8d6f":{
      "scriptId":"u65",
      "03bd36ac64d041918c6dc3aa6374751a":{
        "scriptId":"u66"},
      "df66acca03bf499aa135bbcb6227b967":{
        "scriptId":"u67"},
      "6b692c7b87a3402b9ce9a61959969a10":{
        "scriptId":"u68"},
      "8c6cdd631e4d43428f7d756760855ef4":{
        "scriptId":"u69"},
      "ff8b4a4f418f41888cc0cac89e0b6cc6":{
        "scriptId":"u70"},
      "95d3026929da487595c46ec0c6ac3c87":{
        "scriptId":"u71"},
      "7afee1299b2b48a8a6be957ef89fe2af":{
        "scriptId":"u72"},
      "cc8fa126bf8e4cc6a842e757b7b28f3f":{
        "scriptId":"u73"},
      "b796130b619e4ad2b19a50e713cbbd40":{
        "scriptId":"u74"},
      "6b0b3db928fd4bdc8935f7e7b7748902":{
        "scriptId":"u75"},
      "ef5b7a53388f4425b08610aa93a79189":{
        "scriptId":"u76"},
      "5d9fbdea8ac94145a0e1dac4db9bfff5":{
        "scriptId":"u77"},
      "a13a6ce77356497b9dcac880c9acd548":{
        "scriptId":"u78"},
      "4416e82b29c84e7cb040527f4c8a5b03":{
        "scriptId":"u79"},
      "01bcdd63c23f4cdd8d8a524437ac1102":{
        "scriptId":"u80"},
      "82d50f80e0ba46fc820d9a4ca86db1f1":{
        "scriptId":"u81"},
      "eabd7026a24944e1a21cd8e4f0df4689":{
        "scriptId":"u82"},
      "7cd7f6c343744aaf975767f39e9ee417":{
        "scriptId":"u83"}},
    "49617adce23a41dcaadbe1c587a59822":{
      "scriptId":"u84"},
    "8e9c65d2b55349a7999cd5c7ea740f21":{
      "scriptId":"u85"},
    "f642e057fe9d460082f8f5b7b7973a55":{
      "scriptId":"u86"},
    "2d5e057713de409ab4173d31beee73b8":{
      "scriptId":"u87"},
    "35736b9ce89a4b64a552c49ffee87284":{
      "scriptId":"u88"},
    "b95dfd2a6b8a476f8f9fd8f164a21fa1":{
      "scriptId":"u89"},
    "9fb9b165969a40f1b5335037bca1030b":{
      "scriptId":"u90"},
    "f074510dd643404f8c05ed9f03e3f00e":{
      "scriptId":"u91"},
    "93ef014f02be4ce782473bf61f5fb3b4":{
      "scriptId":"u92"},
    "8749611bd4fe47e2bf15a14c5e8684d3":{
      "scriptId":"u93"},
    "85fbf11d2210454196256b440abedf26":{
      "scriptId":"u94"},
    "3c5b38c05eed408189538162dd791de4":{
      "scriptId":"u95"},
    "638ab710e6a84c059ade0f78ed81d291":{
      "scriptId":"u96"},
    "5b7ba806ea98403aa24e304dc6dd9912":{
      "scriptId":"u97"},
    "a91c65dc8de5407e9b9bf264e56992c0":{
      "scriptId":"u98"},
    "3ddf9158f84d414cacfa4340786b0575":{
      "scriptId":"u99"},
    "fa75534821a24cd1883bf75185675041":{
      "scriptId":"u100"},
    "e39d6b2dd3374c08a538acda43098942":{
      "scriptId":"u101"},
    "b79bf24248724262bcda69cc73a1a4c9":{
      "scriptId":"u102"},
    "cb73a578590b470c90f2a009c8764271":{
      "scriptId":"u103"},
    "eac330afda424d45ae8a5246ab177e1f":{
      "scriptId":"u104"},
    "20cc722e1be94280a86d687419575d99":{
      "scriptId":"u105"},
    "98de66fbf6da4f689943a0e0976ee3c2":{
      "scriptId":"u106"},
    "18297e112ebb4d2f80cb7ff1bd1c0818":{
      "scriptId":"u107"},
    "976f5b84e7444c5cbeaa16a9b642066b":{
      "scriptId":"u108"},
    "a1073edd14c14360b5d6ca84ed961c25":{
      "scriptId":"u109"},
    "fc645e9df49b4f6599fa080153a8c496":{
      "scriptId":"u110"}}});