$axure.loadCurrentPage({
  "url":"业务线信息.html",
  "generationDate":new Date(1488533172407.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8cca7aa5dd5749018190b58693315131",
    "type":"Axure:Page",
    "name":"业务线信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e1079ad5356146df83696284c11c103c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":322,
              "y":80},
            "size":{
              "width":798,
              "height":232}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29344bfa0f0b40d6bdba9abb325f0e3c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":322,
                  "y":80},
                "size":{
                  "width":798,
                  "height":232}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6ab6e761e07b4d84942fbfda394b4d2d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":356,
              "y":338},
            "size":{
              "width":724,
              "height":156}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4041fbea32244ed48cb8eb642ad4b494",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":86,
                  "y":0},
                "size":{
                  "width":219,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"821f5031e15248d3ae6533653095f855",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":86,
                      "y":0},
                    "size":{
                      "width":219,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u5.png"}},
{
              "id":"3d2eb07d08f344189aeccd03d7a970e6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":86,
                  "y":36},
                "size":{
                  "width":219,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a25cba843e1f4f0ab96af418b61745c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":86,
                      "y":36},
                    "size":{
                      "width":219,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 功能分组",
                          "target":{
                            "targetType":"page",
                            "url":"功能分组.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/业务线信息/u13.png"}},
{
              "id":"7e6a5358f52e4fc982490c908cdc09de",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":86,
                  "y":66},
                "size":{
                  "width":219,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9af7888c06c54ac69e7a75d9667d97ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":86,
                      "y":66},
                    "size":{
                      "width":219,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u13.png"}},
{
              "id":"965b3fbd802e4c85a0399765e2b96015",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":86,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5649ca1f82234479a7d59f46dfa01939",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":86,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u3.png"}},
{
              "id":"b7806b72dfa94b678e0efb164e324e80",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":86,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"14422435dcef41f78eb3004aaf770225",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":86,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u11.png"}},
{
              "id":"2b63b0318e0c48e5832690e7f6dad8ce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":86,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e833ad0b5bab4166b8d4998e94f3fc40",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":86,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u11.png"}},
{
              "id":"80633f22370d4558a21c043b97c9622a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":86,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9347b7a9215a4cafbff98ec4dfe61a7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":96},
                    "size":{
                      "width":86,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u11.png"}},
{
              "id":"b5c038b90fae4f18bebc288eeb06313e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":86,
                  "y":96},
                "size":{
                  "width":219,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"982161141b4d44309bb9c5709b5a1d19",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":86,
                      "y":96},
                    "size":{
                      "width":219,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u13.png"}},
{
              "id":"c1dfda4675cf468d9f2da10baa661cd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":126},
                "size":{
                  "width":86,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e7ff97040bc4470b253f599f202bfa4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":126},
                    "size":{
                      "width":86,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u35.png"}},
{
              "id":"74413987e0d44ec6a56d229e12fb9ff9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":86,
                  "y":126},
                "size":{
                  "width":219,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0935105d983a4104b1dadec16186cbd6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":86,
                      "y":126},
                    "size":{
                      "width":219,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u37.png"}},
{
              "id":"3bf6bb033f7f42fe98614413f8c51c8a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":473,
                  "y":0},
                "size":{
                  "width":251,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0e073e3ea3374721bf63322682ebd769",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":473,
                      "y":0},
                    "size":{
                      "width":251,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u9.png"}},
{
              "id":"6449d4db73144b15929f9c48655959cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":473,
                  "y":36},
                "size":{
                  "width":251,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a42817fe39694d5193e4c3db921257d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":473,
                      "y":36},
                    "size":{
                      "width":251,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u17.png"}},
{
              "id":"8aea362a0a6c496fbff5d654ca5c32b7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":473,
                  "y":66},
                "size":{
                  "width":251,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"691f374c5c7d45bc96f94b3adffc8598",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":473,
                      "y":66},
                    "size":{
                      "width":251,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u17.png"}},
{
              "id":"c6780377f7d1468f8c5d38c5d2708362",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":473,
                  "y":96},
                "size":{
                  "width":251,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b7a2bfed23a84e45ae20e5cb2614f5c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":473,
                      "y":96},
                    "size":{
                      "width":251,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u17.png"}},
{
              "id":"600b168a410c43e28de2289c9356ecaf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":473,
                  "y":126},
                "size":{
                  "width":251,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dde007df7b8b4f81b1106444bc508615",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":473,
                      "y":126},
                    "size":{
                      "width":251,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u41.png"}},
{
              "id":"c65662f1c72e486b83cbcb30ffc2ec18",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":305,
                  "y":0},
                "size":{
                  "width":168,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b0823805c5ca4dabb84ebe7eff3fe0ba",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":305,
                      "y":0},
                    "size":{
                      "width":168,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u7.png"}},
{
              "id":"98644f3a63e147e4aa64ffd422529bcb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":305,
                  "y":36},
                "size":{
                  "width":168,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c243d1c9d455459891c61c2fc9f9af69",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":305,
                      "y":36},
                    "size":{
                      "width":168,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u15.png"}},
{
              "id":"ec39a6bde8d24bb99874f7076427a900",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":305,
                  "y":66},
                "size":{
                  "width":168,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6a68ea339a143108255e02de4b061f3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":305,
                      "y":66},
                    "size":{
                      "width":168,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u15.png"}},
{
              "id":"f5b463fa96d74ac3b39c1f077713e99a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":305,
                  "y":96},
                "size":{
                  "width":168,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"373b32fe35954e759646539ffd4f0296",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":305,
                      "y":96},
                    "size":{
                      "width":168,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u15.png"}},
{
              "id":"5cfde653db3a4de69391e508bc6de7af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":305,
                  "y":126},
                "size":{
                  "width":168,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2982c050bc54ac8a8dd9a95672ffbf9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":305,
                      "y":126},
                    "size":{
                      "width":168,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务线信息/u39.png"}}]},
{
          "id":"5f11cf35e2da45d19ad19109c5875c0b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":346},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"995495e20b6f42fd991e0380655d1de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":346},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"31c0427166a144d7b1c945d30c0381f2",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":377},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef0312adb87040d6a95c453bb122cac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":377},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d9b7440923dd42198a972e0420421c92",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":408},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09cabda4de7d43718ad58a7d6d24883c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":408},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1a5af0215fd44a12b0e267104e9961fd",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":438},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a16eb8559cc5451b9ab726d8a3781481",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":438},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"968b485393fe470c8da6ceab808fd2a0",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":469},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeeb293cd41b439d91782a3a1e8cb5d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":469},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3003a9d004704e59a47be99330814315",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"7a02efa0d5604338a3be75f38bcf2b86"},
{
          "id":"45f2b264de0b431aac8ecfc3bee8437f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1118,
              "y":376},
            "size":{
              "width":132,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3afa8a524b5b4140bd13bcf51ca9c2cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1118,
                  "y":376},
                "size":{
                  "width":132,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d9b52c14d384932990c519589b70cb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":140,
              "y":117},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a2d70d3e4cc4b6392106374b264734b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":140,
                  "y":117},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 API接口审核",
                      "target":{
                        "targetType":"page",
                        "url":"api接口审核.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/开发者认证审核/u19.png"}},
{
          "id":"fd047ceb9bab4b48950891a3e9bb6e35",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":510},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "7a02efa0d5604338a3be75f38bcf2b86":{
      "packageId":"7a02efa0d5604338a3be75f38bcf2b86",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"03bd36ac64d041918c6dc3aa6374751a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df66acca03bf499aa135bbcb6227b967",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"6b692c7b87a3402b9ce9a61959969a10",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0099FF,
                "opacity":1},
              "location":{
                "x":59,
                "y":18},
              "size":{
                "width":241,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c6cdd631e4d43428f7d756760855ef4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0099FF,
                    "opacity":1},
                  "location":{
                    "x":59,
                    "y":18},
                  "size":{
                    "width":241,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ff8b4a4f418f41888cc0cac89e0b6cc6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":59},
              "size":{
                "width":200,
                "height":421}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"95d3026929da487595c46ec0c6ac3c87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":59},
                  "size":{
                    "width":200,
                    "height":421}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u5.png"}},
{
            "id":"7afee1299b2b48a8a6be957ef89fe2af",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":59},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc8fa126bf8e4cc6a842e757b7b28f3f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":59},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API提供者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"api提供者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"b796130b619e4ad2b19a50e713cbbd40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":88},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b0b3db928fd4bdc8935f7e7b7748902",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":88},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 开发者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"开发者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"ef5b7a53388f4425b08610aa93a79189",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":175},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d9fbdea8ac94145a0e1dac4db9bfff5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":175},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 应用上线审核",
                        "target":{
                          "targetType":"page",
                          "url":"应用上线审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"a13a6ce77356497b9dcac880c9acd548",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":117},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4416e82b29c84e7cb040527f4c8a5b03",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":117},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API接口审核",
                        "target":{
                          "targetType":"page",
                          "url":"api接口审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"01bcdd63c23f4cdd8d8a524437ac1102",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":146},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82d50f80e0ba46fc820d9a4ca86db1f1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":146},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 接入指南审核",
                        "target":{
                          "targetType":"page",
                          "url":"接入指南审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"eabd7026a24944e1a21cd8e4f0df4689",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":204},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7cd7f6c343744aaf975767f39e9ee417",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":204},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 申请功能分组申请",
                        "target":{
                          "targetType":"page",
                          "url":"申请功能分组申请.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}}]}}},
  "objectPaths":{
    "e1079ad5356146df83696284c11c103c":{
      "scriptId":"u0"},
    "29344bfa0f0b40d6bdba9abb325f0e3c":{
      "scriptId":"u1"},
    "6ab6e761e07b4d84942fbfda394b4d2d":{
      "scriptId":"u2"},
    "965b3fbd802e4c85a0399765e2b96015":{
      "scriptId":"u3"},
    "5649ca1f82234479a7d59f46dfa01939":{
      "scriptId":"u4"},
    "4041fbea32244ed48cb8eb642ad4b494":{
      "scriptId":"u5"},
    "821f5031e15248d3ae6533653095f855":{
      "scriptId":"u6"},
    "c65662f1c72e486b83cbcb30ffc2ec18":{
      "scriptId":"u7"},
    "b0823805c5ca4dabb84ebe7eff3fe0ba":{
      "scriptId":"u8"},
    "3bf6bb033f7f42fe98614413f8c51c8a":{
      "scriptId":"u9"},
    "0e073e3ea3374721bf63322682ebd769":{
      "scriptId":"u10"},
    "b7806b72dfa94b678e0efb164e324e80":{
      "scriptId":"u11"},
    "14422435dcef41f78eb3004aaf770225":{
      "scriptId":"u12"},
    "3d2eb07d08f344189aeccd03d7a970e6":{
      "scriptId":"u13"},
    "a25cba843e1f4f0ab96af418b61745c8":{
      "scriptId":"u14"},
    "98644f3a63e147e4aa64ffd422529bcb":{
      "scriptId":"u15"},
    "c243d1c9d455459891c61c2fc9f9af69":{
      "scriptId":"u16"},
    "6449d4db73144b15929f9c48655959cc":{
      "scriptId":"u17"},
    "a42817fe39694d5193e4c3db921257d8":{
      "scriptId":"u18"},
    "2b63b0318e0c48e5832690e7f6dad8ce":{
      "scriptId":"u19"},
    "e833ad0b5bab4166b8d4998e94f3fc40":{
      "scriptId":"u20"},
    "7e6a5358f52e4fc982490c908cdc09de":{
      "scriptId":"u21"},
    "9af7888c06c54ac69e7a75d9667d97ba":{
      "scriptId":"u22"},
    "ec39a6bde8d24bb99874f7076427a900":{
      "scriptId":"u23"},
    "e6a68ea339a143108255e02de4b061f3":{
      "scriptId":"u24"},
    "8aea362a0a6c496fbff5d654ca5c32b7":{
      "scriptId":"u25"},
    "691f374c5c7d45bc96f94b3adffc8598":{
      "scriptId":"u26"},
    "80633f22370d4558a21c043b97c9622a":{
      "scriptId":"u27"},
    "9347b7a9215a4cafbff98ec4dfe61a7e":{
      "scriptId":"u28"},
    "b5c038b90fae4f18bebc288eeb06313e":{
      "scriptId":"u29"},
    "982161141b4d44309bb9c5709b5a1d19":{
      "scriptId":"u30"},
    "f5b463fa96d74ac3b39c1f077713e99a":{
      "scriptId":"u31"},
    "373b32fe35954e759646539ffd4f0296":{
      "scriptId":"u32"},
    "c6780377f7d1468f8c5d38c5d2708362":{
      "scriptId":"u33"},
    "b7a2bfed23a84e45ae20e5cb2614f5c8":{
      "scriptId":"u34"},
    "c1dfda4675cf468d9f2da10baa661cd8":{
      "scriptId":"u35"},
    "7e7ff97040bc4470b253f599f202bfa4":{
      "scriptId":"u36"},
    "74413987e0d44ec6a56d229e12fb9ff9":{
      "scriptId":"u37"},
    "0935105d983a4104b1dadec16186cbd6":{
      "scriptId":"u38"},
    "5cfde653db3a4de69391e508bc6de7af":{
      "scriptId":"u39"},
    "f2982c050bc54ac8a8dd9a95672ffbf9":{
      "scriptId":"u40"},
    "600b168a410c43e28de2289c9356ecaf":{
      "scriptId":"u41"},
    "dde007df7b8b4f81b1106444bc508615":{
      "scriptId":"u42"},
    "5f11cf35e2da45d19ad19109c5875c0b":{
      "scriptId":"u43"},
    "995495e20b6f42fd991e0380655d1de4":{
      "scriptId":"u44"},
    "31c0427166a144d7b1c945d30c0381f2":{
      "scriptId":"u45"},
    "ef0312adb87040d6a95c453bb122cac7":{
      "scriptId":"u46"},
    "d9b7440923dd42198a972e0420421c92":{
      "scriptId":"u47"},
    "09cabda4de7d43718ad58a7d6d24883c":{
      "scriptId":"u48"},
    "1a5af0215fd44a12b0e267104e9961fd":{
      "scriptId":"u49"},
    "a16eb8559cc5451b9ab726d8a3781481":{
      "scriptId":"u50"},
    "968b485393fe470c8da6ceab808fd2a0":{
      "scriptId":"u51"},
    "aeeb293cd41b439d91782a3a1e8cb5d2":{
      "scriptId":"u52"},
    "3003a9d004704e59a47be99330814315":{
      "scriptId":"u53",
      "03bd36ac64d041918c6dc3aa6374751a":{
        "scriptId":"u54"},
      "df66acca03bf499aa135bbcb6227b967":{
        "scriptId":"u55"},
      "6b692c7b87a3402b9ce9a61959969a10":{
        "scriptId":"u56"},
      "8c6cdd631e4d43428f7d756760855ef4":{
        "scriptId":"u57"},
      "ff8b4a4f418f41888cc0cac89e0b6cc6":{
        "scriptId":"u58"},
      "95d3026929da487595c46ec0c6ac3c87":{
        "scriptId":"u59"},
      "7afee1299b2b48a8a6be957ef89fe2af":{
        "scriptId":"u60"},
      "cc8fa126bf8e4cc6a842e757b7b28f3f":{
        "scriptId":"u61"},
      "b796130b619e4ad2b19a50e713cbbd40":{
        "scriptId":"u62"},
      "6b0b3db928fd4bdc8935f7e7b7748902":{
        "scriptId":"u63"},
      "ef5b7a53388f4425b08610aa93a79189":{
        "scriptId":"u64"},
      "5d9fbdea8ac94145a0e1dac4db9bfff5":{
        "scriptId":"u65"},
      "a13a6ce77356497b9dcac880c9acd548":{
        "scriptId":"u66"},
      "4416e82b29c84e7cb040527f4c8a5b03":{
        "scriptId":"u67"},
      "01bcdd63c23f4cdd8d8a524437ac1102":{
        "scriptId":"u68"},
      "82d50f80e0ba46fc820d9a4ca86db1f1":{
        "scriptId":"u69"},
      "eabd7026a24944e1a21cd8e4f0df4689":{
        "scriptId":"u70"},
      "7cd7f6c343744aaf975767f39e9ee417":{
        "scriptId":"u71"}},
    "45f2b264de0b431aac8ecfc3bee8437f":{
      "scriptId":"u72"},
    "3afa8a524b5b4140bd13bcf51ca9c2cf":{
      "scriptId":"u73"},
    "0d9b52c14d384932990c519589b70cb2":{
      "scriptId":"u74"},
    "3a2d70d3e4cc4b6392106374b264734b":{
      "scriptId":"u75"},
    "fd047ceb9bab4b48950891a3e9bb6e35":{
      "scriptId":"u76"}}});