$axure.loadCurrentPage({
  "url":"申请功能分组申请.html",
  "generationDate":new Date(1488533173286.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c8ba9759d56d4b15b5bcce96f131384e",
    "type":"Axure:Page",
    "name":"申请功能分组申请",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e13838100a404043a67e52b63022ea7d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"7a02efa0d5604338a3be75f38bcf2b86"},
{
          "id":"1c18d5abd80645e6884a44c373257c3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":87},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"509c45b0d5c54551af01b9b073ff048e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":87},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3813c972f5a9465b9a97f0d92073dbda",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":83},
            "size":{
              "width":151,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c083362cf54a4c619f41dbfff24a7c4e",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":160},
            "size":{
              "width":739,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fa00be9fd8244a5a40d9180cd2c43ba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":74,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc7d843d73c9449ea527f9a6d4cf677e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":74,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南列表/u11.png"}},
{
              "id":"6061527b4b404345a87f70d6972ec952",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":74,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"025023c4c38d4f289f34ec99959f60ef",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":74,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南列表/u11.png"}},
{
              "id":"f1c794aa03fc44a3a89163bab0f35f24",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":36},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29ed38a617a04793b68902377b7b3c57",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":36},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u39.png"}},
{
              "id":"c77f8c04570a45aba6a91ed696397df5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":66},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9f3bdf288ae84524992065e2a869b882",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":66},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u39.png"}},
{
              "id":"81f0d6fa197a44cda437cb052acd1756",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":357,
                  "y":36},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4517e62d26ca4237b4d79e0ddd6cb190",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":357,
                      "y":36},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u39.png"}},
{
              "id":"961d856fa5a4452cb3a9bf2c4889b8c4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":357,
                  "y":66},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"59f4708e3d6148f2ae9580cfcb036e06",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":357,
                      "y":66},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u39.png"}},
{
              "id":"e32920ae2a514ad9a42c0ecea32e22a4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":36},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d50ac29d011445a38b2aaac2803df83f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":646,
                      "y":36},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u45.png"}},
{
              "id":"b3878dd2fa4440d6b9be84f1d19caa80",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":66},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7e5bba8548d483482267642a70eefb5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":646,
                      "y":66},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u45.png"}},
{
              "id":"6efded58387d43d1aa707a6e7b4ff954",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":512,
                  "y":36},
                "size":{
                  "width":134,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6dba79d534664cf9be46910f1be8d959",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":512,
                      "y":36},
                    "size":{
                      "width":134,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u43.png"}},
{
              "id":"43017b76dedd433c8f18da3c2cd46916",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":512,
                  "y":66},
                "size":{
                  "width":134,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"83784a8b9458420ea20349892b95320e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":512,
                      "y":66},
                    "size":{
                      "width":134,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u43.png"}},
{
              "id":"a07338d2258b4f2dbfccae52b50d3c14",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":74,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2b6df3a5e574f0c8e52137f244645c8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":74,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u23.png"}},
{
              "id":"2d7aea0853634097a3f2e841ff24708d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":202,
                  "y":0},
                "size":{
                  "width":155,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"72e3d5c512d548c98b4ff03e02ddc8fd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":202,
                      "y":0},
                    "size":{
                      "width":155,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u27.png"}},
{
              "id":"8fb25f2542374ed1a251eac7619bf2b3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":357,
                  "y":0},
                "size":{
                  "width":155,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ec31eccfcc4c4fa7ada6a8756c403469",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":357,
                      "y":0},
                    "size":{
                      "width":155,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u27.png"}},
{
              "id":"506e18e6dd854e82a499d0bf47d6472d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":512,
                  "y":0},
                "size":{
                  "width":134,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9b46fc6a40974a12838c287fa6ec04fe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":512,
                      "y":0},
                    "size":{
                      "width":134,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u31.png"}},
{
              "id":"9c3bb3c2bab7459baa416d6ac6729163",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":646,
                  "y":0},
                "size":{
                  "width":93,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d31e5e363720435c8a9a5ee9946743cc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":646,
                      "y":0},
                    "size":{
                      "width":93,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u33.png"}},
{
              "id":"ee415eb2a5f84dd7887ebfb54347ef9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":74,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b05a639a116f44a6a009f8127f7cd96a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":96},
                    "size":{
                      "width":74,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南列表/u27.png"}},
{
              "id":"b21a1e67583945f197453d2d5e047790",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":202,
                  "y":96},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"00fca8df3b1842678a35bcdf31151b7d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":202,
                      "y":96},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u63.png"}},
{
              "id":"461dd94d611f47a98adac66f2992b367",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":357,
                  "y":96},
                "size":{
                  "width":155,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"16326974f9a14d868a0c982937bb61b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":357,
                      "y":96},
                    "size":{
                      "width":155,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u63.png"}},
{
              "id":"feba76d42ce74ad3b423b910dbce0a95",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":512,
                  "y":96},
                "size":{
                  "width":134,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ba944755823c41238ed6f2a0964d77cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":512,
                      "y":96},
                    "size":{
                      "width":134,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u67.png"}},
{
              "id":"10b74cf7f36a490aa10e114c66253b2c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":646,
                  "y":96},
                "size":{
                  "width":93,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cea97cb3ad3140fabccac97a18c5fe93",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":646,
                      "y":96},
                    "size":{
                      "width":93,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u69.png"}},
{
              "id":"ea1f9b68097e41f3b28de16259768a68",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":74,
                  "y":0},
                "size":{
                  "width":128,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d4f9395fab2140ab952791c917d61012",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":74,
                      "y":0},
                    "size":{
                      "width":128,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u25.png"}},
{
              "id":"ebb2d51b604e4a46b732db9c420cef99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":36},
                "size":{
                  "width":128,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9e74d65e60714da99e01b1bb98cf3f2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":74,
                      "y":36},
                    "size":{
                      "width":128,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 功能组信息",
                          "target":{
                            "targetType":"page",
                            "url":"功能组信息.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/申请功能分组申请/u37.png"}},
{
              "id":"ca7593fc9f0a416793ac84c65247dcbb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":66},
                "size":{
                  "width":128,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"92e78efb48154ca28ebeb52f7a1c1933",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":74,
                      "y":66},
                    "size":{
                      "width":128,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u37.png"}},
{
              "id":"246ab6ec060848c1b4b768099ee16938",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":74,
                  "y":96},
                "size":{
                  "width":128,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b08dbd19589947179dc011bb9d108745",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":74,
                      "y":96},
                    "size":{
                      "width":128,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u61.png"}}]},
{
          "id":"e2ad98e748d1496b9c94f2f5a1c18d74",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":930,
              "y":83},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6800a11de2ea4bc3a5571b16002f23a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":359},
            "size":{
              "width":340,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"774b4b6078a44608b44329ae9dc13f4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":359},
                "size":{
                  "width":340,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u82.png"}},
{
          "id":"322be24883824b21803c605cebebb19d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":340},
            "size":{
              "width":340,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd2a55fd52f648cf9ed58063785ada57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":340},
                "size":{
                  "width":340,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u84.png"}},
{
          "id":"7623fc884bee49bb888b4315b0829a56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":400},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5471cc38eab048f1850a09e4cf04ebef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":400},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"07c601e8357e46ce9af2e3f00dadf8c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":391},
            "size":{
              "width":70,
              "height":40},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"843c5313342b4a77a2e7e6c4472abc89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":391},
                "size":{
                  "width":70,
                  "height":40},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/api提供者认证审核/u88.png"}},
{
          "id":"3f7655920c634831abe090e26cb078d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":391},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6e613e6ed914427aad59df6c1f08baf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":565,
                  "y":391},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u88.png"}},
{
          "id":"fee9c339b9334edfafd3689496608c93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":452},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef96f1c4d9b4454389db2d639de099e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":452},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"840667d9c96a47b29b39ac0e560053ac",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":448},
            "size":{
              "width":220,
              "height":62}},
          "adaptiveStyles":{
}},
{
          "id":"85a1cd9acb484703bf33b915f338fbc9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":540},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6a2d2102ddf4469b8d6fc49504b72e6d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":540},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c3355c05f0e8467088bcec46ff984a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":650,
              "y":87},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6db3968266ad4a53a21effa2d79efdad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":650,
                  "y":87},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df7dcac1216d44c5b32e79b5a39ed806",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":84},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"527e23faac3e43b7907eb0f5a72ba403",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":140,
              "y":204},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91388dd35a634f37bff4265653ca2620",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":140,
                  "y":204},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 申请功能分组申请",
                      "target":{
                        "targetType":"page",
                        "url":"申请功能分组申请.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/开发者认证审核/u19.png"}},
{
          "id":"b7773fe5b86f4d0e9e66c4d24400a3e0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":320}},
          "adaptiveStyles":{
},
          "masterId":"73a894822cb04a979991d5c2fe28869c"}]}},
  "masters":{
    "7a02efa0d5604338a3be75f38bcf2b86":{
      "packageId":"7a02efa0d5604338a3be75f38bcf2b86",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"03bd36ac64d041918c6dc3aa6374751a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df66acca03bf499aa135bbcb6227b967",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"6b692c7b87a3402b9ce9a61959969a10",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0099FF,
                "opacity":1},
              "location":{
                "x":59,
                "y":18},
              "size":{
                "width":241,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c6cdd631e4d43428f7d756760855ef4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0099FF,
                    "opacity":1},
                  "location":{
                    "x":59,
                    "y":18},
                  "size":{
                    "width":241,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ff8b4a4f418f41888cc0cac89e0b6cc6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":59},
              "size":{
                "width":200,
                "height":421}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"95d3026929da487595c46ec0c6ac3c87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":59},
                  "size":{
                    "width":200,
                    "height":421}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u5.png"}},
{
            "id":"7afee1299b2b48a8a6be957ef89fe2af",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":59},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc8fa126bf8e4cc6a842e757b7b28f3f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":59},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API提供者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"api提供者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"b796130b619e4ad2b19a50e713cbbd40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":88},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b0b3db928fd4bdc8935f7e7b7748902",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":88},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 开发者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"开发者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"ef5b7a53388f4425b08610aa93a79189",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":175},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d9fbdea8ac94145a0e1dac4db9bfff5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":175},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 应用上线审核",
                        "target":{
                          "targetType":"page",
                          "url":"应用上线审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"a13a6ce77356497b9dcac880c9acd548",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":117},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4416e82b29c84e7cb040527f4c8a5b03",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":117},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API接口审核",
                        "target":{
                          "targetType":"page",
                          "url":"api接口审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"01bcdd63c23f4cdd8d8a524437ac1102",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":146},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82d50f80e0ba46fc820d9a4ca86db1f1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":146},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 接入指南审核",
                        "target":{
                          "targetType":"page",
                          "url":"接入指南审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"eabd7026a24944e1a21cd8e4f0df4689",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":204},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7cd7f6c343744aaf975767f39e9ee417",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":204},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 申请功能分组申请",
                        "target":{
                          "targetType":"page",
                          "url":"申请功能分组申请.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}}]}},
    "73a894822cb04a979991d5c2fe28869c":{
      "packageId":"73a894822cb04a979991d5c2fe28869c",
      "type":"Axure:Master",
      "name":"翻页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"10d52bd26dc1429d999b03125a9c30cd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF009DD9},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b19aa526c55b43a09d0a1f52cdf59b18",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF009DD9},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/开发者认证审核/u108.png"}},
{
            "id":"f26fa46f0dbc4366a6042205121f2c66",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":39,
                "y":0},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"72a52d57282b4c4c80e48c143aecd9af",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":39,
                    "y":0},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/开发者认证审核/u110.png"}},
{
            "id":"14683dc145f9469990d88e014b997a79",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":77,
                "y":0},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6f1500a0a1d464cb746d76763b7800e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":77,
                    "y":0},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/开发者认证审核/u110.png"}},
{
            "id":"89b2005568934e69a9300a402254f159",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":154,
                "y":10},
              "size":{
                "width":116,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c2eef9ed5dc14494acf888eb6c387fe9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":154,
                    "y":10},
                  "size":{
                    "width":116,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3b9121491e514f7a847a64d546b1ae1f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":192,
                "y":2.5},
              "size":{
                "width":50,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"ec6df84c54834a539dede8852c0eb792",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":116,
                "y":0},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da38fc0fa4884178a9be73b9e6074536",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":116,
                    "y":0},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/开发者认证审核/u110.png"}}]}}},
  "objectPaths":{
    "e13838100a404043a67e52b63022ea7d":{
      "scriptId":"u0",
      "03bd36ac64d041918c6dc3aa6374751a":{
        "scriptId":"u1"},
      "df66acca03bf499aa135bbcb6227b967":{
        "scriptId":"u2"},
      "6b692c7b87a3402b9ce9a61959969a10":{
        "scriptId":"u3"},
      "8c6cdd631e4d43428f7d756760855ef4":{
        "scriptId":"u4"},
      "ff8b4a4f418f41888cc0cac89e0b6cc6":{
        "scriptId":"u5"},
      "95d3026929da487595c46ec0c6ac3c87":{
        "scriptId":"u6"},
      "7afee1299b2b48a8a6be957ef89fe2af":{
        "scriptId":"u7"},
      "cc8fa126bf8e4cc6a842e757b7b28f3f":{
        "scriptId":"u8"},
      "b796130b619e4ad2b19a50e713cbbd40":{
        "scriptId":"u9"},
      "6b0b3db928fd4bdc8935f7e7b7748902":{
        "scriptId":"u10"},
      "ef5b7a53388f4425b08610aa93a79189":{
        "scriptId":"u11"},
      "5d9fbdea8ac94145a0e1dac4db9bfff5":{
        "scriptId":"u12"},
      "a13a6ce77356497b9dcac880c9acd548":{
        "scriptId":"u13"},
      "4416e82b29c84e7cb040527f4c8a5b03":{
        "scriptId":"u14"},
      "01bcdd63c23f4cdd8d8a524437ac1102":{
        "scriptId":"u15"},
      "82d50f80e0ba46fc820d9a4ca86db1f1":{
        "scriptId":"u16"},
      "eabd7026a24944e1a21cd8e4f0df4689":{
        "scriptId":"u17"},
      "7cd7f6c343744aaf975767f39e9ee417":{
        "scriptId":"u18"}},
    "1c18d5abd80645e6884a44c373257c3c":{
      "scriptId":"u19"},
    "509c45b0d5c54551af01b9b073ff048e":{
      "scriptId":"u20"},
    "3813c972f5a9465b9a97f0d92073dbda":{
      "scriptId":"u21"},
    "c083362cf54a4c619f41dbfff24a7c4e":{
      "scriptId":"u22"},
    "a07338d2258b4f2dbfccae52b50d3c14":{
      "scriptId":"u23"},
    "a2b6df3a5e574f0c8e52137f244645c8":{
      "scriptId":"u24"},
    "ea1f9b68097e41f3b28de16259768a68":{
      "scriptId":"u25"},
    "d4f9395fab2140ab952791c917d61012":{
      "scriptId":"u26"},
    "2d7aea0853634097a3f2e841ff24708d":{
      "scriptId":"u27"},
    "72e3d5c512d548c98b4ff03e02ddc8fd":{
      "scriptId":"u28"},
    "8fb25f2542374ed1a251eac7619bf2b3":{
      "scriptId":"u29"},
    "ec31eccfcc4c4fa7ada6a8756c403469":{
      "scriptId":"u30"},
    "506e18e6dd854e82a499d0bf47d6472d":{
      "scriptId":"u31"},
    "9b46fc6a40974a12838c287fa6ec04fe":{
      "scriptId":"u32"},
    "9c3bb3c2bab7459baa416d6ac6729163":{
      "scriptId":"u33"},
    "d31e5e363720435c8a9a5ee9946743cc":{
      "scriptId":"u34"},
    "9fa00be9fd8244a5a40d9180cd2c43ba":{
      "scriptId":"u35"},
    "dc7d843d73c9449ea527f9a6d4cf677e":{
      "scriptId":"u36"},
    "ebb2d51b604e4a46b732db9c420cef99":{
      "scriptId":"u37"},
    "9e74d65e60714da99e01b1bb98cf3f2d":{
      "scriptId":"u38"},
    "f1c794aa03fc44a3a89163bab0f35f24":{
      "scriptId":"u39"},
    "29ed38a617a04793b68902377b7b3c57":{
      "scriptId":"u40"},
    "81f0d6fa197a44cda437cb052acd1756":{
      "scriptId":"u41"},
    "4517e62d26ca4237b4d79e0ddd6cb190":{
      "scriptId":"u42"},
    "6efded58387d43d1aa707a6e7b4ff954":{
      "scriptId":"u43"},
    "6dba79d534664cf9be46910f1be8d959":{
      "scriptId":"u44"},
    "e32920ae2a514ad9a42c0ecea32e22a4":{
      "scriptId":"u45"},
    "d50ac29d011445a38b2aaac2803df83f":{
      "scriptId":"u46"},
    "6061527b4b404345a87f70d6972ec952":{
      "scriptId":"u47"},
    "025023c4c38d4f289f34ec99959f60ef":{
      "scriptId":"u48"},
    "ca7593fc9f0a416793ac84c65247dcbb":{
      "scriptId":"u49"},
    "92e78efb48154ca28ebeb52f7a1c1933":{
      "scriptId":"u50"},
    "c77f8c04570a45aba6a91ed696397df5":{
      "scriptId":"u51"},
    "9f3bdf288ae84524992065e2a869b882":{
      "scriptId":"u52"},
    "961d856fa5a4452cb3a9bf2c4889b8c4":{
      "scriptId":"u53"},
    "59f4708e3d6148f2ae9580cfcb036e06":{
      "scriptId":"u54"},
    "43017b76dedd433c8f18da3c2cd46916":{
      "scriptId":"u55"},
    "83784a8b9458420ea20349892b95320e":{
      "scriptId":"u56"},
    "b3878dd2fa4440d6b9be84f1d19caa80":{
      "scriptId":"u57"},
    "d7e5bba8548d483482267642a70eefb5":{
      "scriptId":"u58"},
    "ee415eb2a5f84dd7887ebfb54347ef9b":{
      "scriptId":"u59"},
    "b05a639a116f44a6a009f8127f7cd96a":{
      "scriptId":"u60"},
    "246ab6ec060848c1b4b768099ee16938":{
      "scriptId":"u61"},
    "b08dbd19589947179dc011bb9d108745":{
      "scriptId":"u62"},
    "b21a1e67583945f197453d2d5e047790":{
      "scriptId":"u63"},
    "00fca8df3b1842678a35bcdf31151b7d":{
      "scriptId":"u64"},
    "461dd94d611f47a98adac66f2992b367":{
      "scriptId":"u65"},
    "16326974f9a14d868a0c982937bb61b8":{
      "scriptId":"u66"},
    "feba76d42ce74ad3b423b910dbce0a95":{
      "scriptId":"u67"},
    "ba944755823c41238ed6f2a0964d77cb":{
      "scriptId":"u68"},
    "10b74cf7f36a490aa10e114c66253b2c":{
      "scriptId":"u69"},
    "cea97cb3ad3140fabccac97a18c5fe93":{
      "scriptId":"u70"},
    "e2ad98e748d1496b9c94f2f5a1c18d74":{
      "scriptId":"u71"},
    "6800a11de2ea4bc3a5571b16002f23a2":{
      "scriptId":"u72"},
    "774b4b6078a44608b44329ae9dc13f4f":{
      "scriptId":"u73"},
    "322be24883824b21803c605cebebb19d":{
      "scriptId":"u74"},
    "fd2a55fd52f648cf9ed58063785ada57":{
      "scriptId":"u75"},
    "7623fc884bee49bb888b4315b0829a56":{
      "scriptId":"u76"},
    "5471cc38eab048f1850a09e4cf04ebef":{
      "scriptId":"u77"},
    "07c601e8357e46ce9af2e3f00dadf8c3":{
      "scriptId":"u78"},
    "843c5313342b4a77a2e7e6c4472abc89":{
      "scriptId":"u79"},
    "3f7655920c634831abe090e26cb078d6":{
      "scriptId":"u80"},
    "d6e613e6ed914427aad59df6c1f08baf":{
      "scriptId":"u81"},
    "fee9c339b9334edfafd3689496608c93":{
      "scriptId":"u82"},
    "ef96f1c4d9b4454389db2d639de099e0":{
      "scriptId":"u83"},
    "840667d9c96a47b29b39ac0e560053ac":{
      "scriptId":"u84"},
    "85a1cd9acb484703bf33b915f338fbc9":{
      "scriptId":"u85"},
    "6a2d2102ddf4469b8d6fc49504b72e6d":{
      "scriptId":"u86"},
    "c3355c05f0e8467088bcec46ff984a63":{
      "scriptId":"u87"},
    "6db3968266ad4a53a21effa2d79efdad":{
      "scriptId":"u88"},
    "df7dcac1216d44c5b32e79b5a39ed806":{
      "scriptId":"u89"},
    "527e23faac3e43b7907eb0f5a72ba403":{
      "scriptId":"u90"},
    "91388dd35a634f37bff4265653ca2620":{
      "scriptId":"u91"},
    "b7773fe5b86f4d0e9e66c4d24400a3e0":{
      "scriptId":"u92",
      "10d52bd26dc1429d999b03125a9c30cd":{
        "scriptId":"u93"},
      "b19aa526c55b43a09d0a1f52cdf59b18":{
        "scriptId":"u94"},
      "f26fa46f0dbc4366a6042205121f2c66":{
        "scriptId":"u95"},
      "72a52d57282b4c4c80e48c143aecd9af":{
        "scriptId":"u96"},
      "14683dc145f9469990d88e014b997a79":{
        "scriptId":"u97"},
      "c6f1500a0a1d464cb746d76763b7800e":{
        "scriptId":"u98"},
      "89b2005568934e69a9300a402254f159":{
        "scriptId":"u99"},
      "c2eef9ed5dc14494acf888eb6c387fe9":{
        "scriptId":"u100"},
      "3b9121491e514f7a847a64d546b1ae1f":{
        "scriptId":"u101"},
      "ec6df84c54834a539dede8852c0eb792":{
        "scriptId":"u102"},
      "da38fc0fa4884178a9be73b9e6074536":{
        "scriptId":"u103"}}}});