$axure.loadCurrentPage({
  "url":"接口文档.html",
  "generationDate":new Date(1487728188010.21),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b8b30710de8a4c8da25fc7b37e9db716",
    "type":"Axure:Page",
    "name":"接口文档",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"70997d6682fe4accbecafb49be4400ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":125},
            "size":{
              "width":840,
              "height":1005}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe84feff90f4f7e9d67e85d93649431",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":430,
                  "y":125},
                "size":{
                  "width":840,
                  "height":1005}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"895f8190b04d47a9ac2deec20768667b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6e03aba969a64804a7fa4490ab766812"},
{
          "id":"a8c49ce06f854624af6938c68b9a009b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":99},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0980ae7e6cb0431dbe126731697c3544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":99},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u17.png"}},
{
          "id":"096e89b656a34b1c953b843479fce18a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":138},
            "size":{
              "width":200,
              "height":421}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ee0fdd0c505455ab8f4397b61308e05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":138},
                "size":{
                  "width":200,
                  "height":421}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u19.png"}},
{
          "id":"4b421a7fc14b401288e0309028f83a38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":138},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac66fe8e617a4d629f206e73a3b26fe7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":138},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心-基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心-基本信息/u29.png"}},
{
          "id":"a3c8eeb968bc473aad0496bd63edc462",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":179},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af781c03d5ae4ee5819b2357a1ecce5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":179},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u17.png"}},
{
          "id":"585157aff3ab475e8c48410a1718ea47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":220,
              "y":218},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88fc6b48c08d4e2d95c4ac6f8676551c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":220,
                  "y":218},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 应用管理-有",
                      "target":{
                        "targetType":"page",
                        "url":"应用管理-有.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心-基本信息/u21.png"}},
{
          "id":"99a3f9d114174a4ea28ca9ffdbba8fdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":758,
              "y":1140},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5060ebd19db407eb611cbe276958eca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":758,
                  "y":1140},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 功能信息",
                      "target":{
                        "targetType":"page",
                        "url":"功能信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/应用信息/u2.png"}},
{
          "id":"a40e84acd3664807b56f544cc35371e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":920},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc3f0de977ef4296b55fcd07169f17a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":690,
                  "y":920},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e6205a2c4be04764b0c3170aee9b8477",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":652},
            "size":{
              "width":700,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f70bb82f0ab4a8084c1f223cfb80d8f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"562d9fc420834645a0b799c4729d476e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u2.png"}},
{
              "id":"c50d73f148f74d7392aa06f77317fb99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a31c84c4924048279eccb629637314ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u4.png"}},
{
              "id":"63a7119a584e44afa6efc881d999ba74",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d3df6e96f1145c8a606d99165b85111",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u4.png"}},
{
              "id":"d971fbe9d4fd42cc904776667e5d074a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f7964345533744da9cd95b987c48ec3f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u2.png"}},
{
              "id":"6a6b230a853d4644bb2ef9e2202d9c5e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8acb287794d48bda918dd972d6b8c70",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口文档/u42.png"}},
{
              "id":"90c0fc52616244f19604d06eb456869b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50d8dc1cbd794f1087036b4654546b09",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u14.png"}},
{
              "id":"dbd8fa15327e45a1b0d1a71059912825",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"219114b440ce418ca74cd10700047d2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u16.png"}},
{
              "id":"7a5ffc21a2f443df946c1ee64930eeae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6144b05514b4466986b6c79c34dc306c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u16.png"}},
{
              "id":"ff24730e91db40669ea381ee59dc68bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8f9b028d510a48bd9cb8494a326645b1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u14.png"}},
{
              "id":"30486983718c454c92579acf862522ec",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4223eea2fa74476199dbb971e1021ea6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-基本信息/u17.png"}}]},
{
          "id":"ce2f8f3f09cc42e998e999e7afc750e0",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":508,
              "y":777},
            "size":{
              "width":700,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ab2057381bf4d179d9c3247b4aefbcb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c78f2f88c470408a93be332987d9cc5d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u2.png"}},
{
              "id":"9a37efb03e3b4d698a1c5b51c508e486",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"464914a244754629a2a583a2f98c055e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u4.png"}},
{
              "id":"6cc350c9fec04ce1a18a0f07d49ef74c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d97c0c900e649209ce0ee195ce4ff36",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u4.png"}},
{
              "id":"ef68ead3c3f341c0b7e83e5402a24a0c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"40ab02056e0d4cef8b354edc017ab9ce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u2.png"}},
{
              "id":"f86d2b8499204f9da4c820bf324de499",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f3c2293e15e34433becd030de7ef39cd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口文档/u42.png"}},
{
              "id":"c64763bb9a664d18be85c1e685929957",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a5a2681dc75846a4a80a9dcce1cc0ac0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u14.png"}},
{
              "id":"c34404f34ef64f5ca471e11ad5dd3fd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2f6e27403654ee6906acc82f778c5fe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u16.png"}},
{
              "id":"164ed4f0ec3d4b888910e5257c741553",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0917162059e94e9c8f803d687a876993",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u16.png"}},
{
              "id":"d975540d0d3740c3af45d42abdd8d918",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"baab3bbca28e4be28871166540f7f362",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u14.png"}},
{
              "id":"2380a80482f74c798bb0a15bde87c09c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe7971727bc84b1da59c4a0f6619cddd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-基本信息/u17.png"}}]},
{
          "id":"af7d65a85b634a4191f5fd771f06e358",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":906},
            "size":{
              "width":700,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6778e02625347f487c9395e4fe26134",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cb937d8c1e9841d5851aed068189dfff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u2.png"}},
{
              "id":"e176373882774df9821885da1397c229",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b8655601d6db47d290ca93e76f2ff20a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u4.png"}},
{
              "id":"41fb5d36632544759fd980669ca848c0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"cdc5a4c83971496eb3cd55a18e4aafd2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u4.png"}},
{
              "id":"2375a8536a2349e4b279f5b285446ae7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ba3f5c9e11dd476db13b64b7fbf81126",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u2.png"}},
{
              "id":"e54dce9a082c41f1aefaba7f136de0e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea6a2006e8e4420d83a446bdcd936c62",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口文档/u42.png"}},
{
              "id":"1d9b79159ab9413c9c610da4295a33d6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"142fa9937e974277a8e46b8518f57a21",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u14.png"}},
{
              "id":"ac96c74a5607442eab2708f6a26f3b88",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d88064a0a279487f85ff6f680641816a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u16.png"}},
{
              "id":"48ac2b3c39be446f92440917ea54f135",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4eb2ba79887b4cedbe6f2431319f435d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u16.png"}},
{
              "id":"add4efae56cb44d7addfe75ea2d0b0f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0b124dd60d474aae92f3f708f9419b59",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u14.png"}},
{
              "id":"7dfcb1b8fc944a8ca13676d9bf4fb211",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bb2f3d26c0094cdc8001e2470e65abb6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/个人中心-基本信息/u17.png"}}]},
{
          "id":"96b64967c06e4fcfa579930308dd8f7f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":1035},
            "size":{
              "width":700,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1340cbcbc7b84ef08515e0f006388065",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":200,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"33a8db434fa14d27b8076b64f1ceb36f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":200,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u134.png"}},
{
              "id":"952c12a0dd334a56997684d15ef1ffd7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":500,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b1639c0c159840ffb7966b64ff5e5d0f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":500,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口文档/u99.png"}},
{
              "id":"551337023b2d4bf58096f27f62ee80dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"45e3e87392c7452e9e5cb180f0f48ff5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/上传接口/u22.png"}},
{
              "id":"7791fe4d1cbb420a9f5ae1d86fb5744f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":33},
                "size":{
                  "width":500,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f7e9db20557f407dbbce927921f29ab8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":33},
                    "size":{
                      "width":500,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口文档/u103.png"}}]}]}},
  "masters":{
    "6e03aba969a64804a7fa4490ab766812":{
      "packageId":"6e03aba969a64804a7fa4490ab766812",
      "type":"Axure:Master",
      "name":"banner",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a379bbcedb33484ebee107fd9c00378e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1370,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"623ed66a746d41b3a92930eccc112eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1370,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u1.png"}},
{
            "id":"7e02905f180d444e82bf7a5e5f714ed2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":146,
                "y":40},
              "size":{
                "width":114,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23469a3e4ec040068e7550ebfc87d3fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":146,
                    "y":40},
                  "size":{
                    "width":114,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b922b24f0c8c43d79cb58b86621900a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":25},
              "size":{
                "width":100,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97728730fc9e442e987885d0bedd7b6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":25},
                  "size":{
                    "width":100,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u5.png"}},
{
            "id":"0980d651269a4ee0996ac0911a37f74d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":360,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0890f7341e6a49ddb31eb81acdbadf59",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":360,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-登陆后",
                        "target":{
                          "targetType":"page",
                          "url":"首页-登陆后.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"b85b3c40a072433a8432159a76f4d82c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":510,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"40321ea5c398434fbfe7b32670a82628",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":510,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 应用管理-无",
                        "target":{
                          "targetType":"page",
                          "url":"应用管理-无.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"65cb50f858734024be55b79cf7647867",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":660,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"950e973e89a14b04b6aeb8769318250d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":660,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c5c2818163684e16951f2f96bb2e461e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":810,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f5a0cb72b6d94ce992936281e7e57efa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":810,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c80392740b724ca4a02d640db27ef42d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1176,
                "y":34},
              "size":{
                "width":94,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"574479846c4b4024bf9f32b14cbbf5ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1176,
                    "y":34},
                  "size":{
                    "width":94,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心-基本信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心-基本信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "70997d6682fe4accbecafb49be4400ba":{
      "scriptId":"u0"},
    "afe84feff90f4f7e9d67e85d93649431":{
      "scriptId":"u1"},
    "895f8190b04d47a9ac2deec20768667b":{
      "scriptId":"u2",
      "a379bbcedb33484ebee107fd9c00378e":{
        "scriptId":"u3"},
      "623ed66a746d41b3a92930eccc112eeb":{
        "scriptId":"u4"},
      "7e02905f180d444e82bf7a5e5f714ed2":{
        "scriptId":"u5"},
      "23469a3e4ec040068e7550ebfc87d3fd":{
        "scriptId":"u6"},
      "b922b24f0c8c43d79cb58b86621900a2":{
        "scriptId":"u7"},
      "97728730fc9e442e987885d0bedd7b6d":{
        "scriptId":"u8"},
      "0980d651269a4ee0996ac0911a37f74d":{
        "scriptId":"u9"},
      "0890f7341e6a49ddb31eb81acdbadf59":{
        "scriptId":"u10"},
      "b85b3c40a072433a8432159a76f4d82c":{
        "scriptId":"u11"},
      "40321ea5c398434fbfe7b32670a82628":{
        "scriptId":"u12"},
      "65cb50f858734024be55b79cf7647867":{
        "scriptId":"u13"},
      "950e973e89a14b04b6aeb8769318250d":{
        "scriptId":"u14"},
      "c5c2818163684e16951f2f96bb2e461e":{
        "scriptId":"u15"},
      "f5a0cb72b6d94ce992936281e7e57efa":{
        "scriptId":"u16"},
      "c80392740b724ca4a02d640db27ef42d":{
        "scriptId":"u17"},
      "574479846c4b4024bf9f32b14cbbf5ea":{
        "scriptId":"u18"}},
    "a8c49ce06f854624af6938c68b9a009b":{
      "scriptId":"u19"},
    "0980ae7e6cb0431dbe126731697c3544":{
      "scriptId":"u20"},
    "096e89b656a34b1c953b843479fce18a":{
      "scriptId":"u21"},
    "6ee0fdd0c505455ab8f4397b61308e05":{
      "scriptId":"u22"},
    "4b421a7fc14b401288e0309028f83a38":{
      "scriptId":"u23"},
    "ac66fe8e617a4d629f206e73a3b26fe7":{
      "scriptId":"u24"},
    "a3c8eeb968bc473aad0496bd63edc462":{
      "scriptId":"u25"},
    "af781c03d5ae4ee5819b2357a1ecce5b":{
      "scriptId":"u26"},
    "585157aff3ab475e8c48410a1718ea47":{
      "scriptId":"u27"},
    "88fc6b48c08d4e2d95c4ac6f8676551c":{
      "scriptId":"u28"},
    "99a3f9d114174a4ea28ca9ffdbba8fdd":{
      "scriptId":"u29"},
    "f5060ebd19db407eb611cbe276958eca":{
      "scriptId":"u30"},
    "a40e84acd3664807b56f544cc35371e6":{
      "scriptId":"u31"},
    "cc3f0de977ef4296b55fcd07169f17a5":{
      "scriptId":"u32"},
    "e6205a2c4be04764b0c3170aee9b8477":{
      "scriptId":"u33"},
    "2f70bb82f0ab4a8084c1f223cfb80d8f":{
      "scriptId":"u34"},
    "562d9fc420834645a0b799c4729d476e":{
      "scriptId":"u35"},
    "c50d73f148f74d7392aa06f77317fb99":{
      "scriptId":"u36"},
    "a31c84c4924048279eccb629637314ce":{
      "scriptId":"u37"},
    "63a7119a584e44afa6efc881d999ba74":{
      "scriptId":"u38"},
    "7d3df6e96f1145c8a606d99165b85111":{
      "scriptId":"u39"},
    "d971fbe9d4fd42cc904776667e5d074a":{
      "scriptId":"u40"},
    "f7964345533744da9cd95b987c48ec3f":{
      "scriptId":"u41"},
    "6a6b230a853d4644bb2ef9e2202d9c5e":{
      "scriptId":"u42"},
    "e8acb287794d48bda918dd972d6b8c70":{
      "scriptId":"u43"},
    "90c0fc52616244f19604d06eb456869b":{
      "scriptId":"u44"},
    "50d8dc1cbd794f1087036b4654546b09":{
      "scriptId":"u45"},
    "dbd8fa15327e45a1b0d1a71059912825":{
      "scriptId":"u46"},
    "219114b440ce418ca74cd10700047d2d":{
      "scriptId":"u47"},
    "7a5ffc21a2f443df946c1ee64930eeae":{
      "scriptId":"u48"},
    "6144b05514b4466986b6c79c34dc306c":{
      "scriptId":"u49"},
    "ff24730e91db40669ea381ee59dc68bf":{
      "scriptId":"u50"},
    "8f9b028d510a48bd9cb8494a326645b1":{
      "scriptId":"u51"},
    "30486983718c454c92579acf862522ec":{
      "scriptId":"u52"},
    "4223eea2fa74476199dbb971e1021ea6":{
      "scriptId":"u53"},
    "ce2f8f3f09cc42e998e999e7afc750e0":{
      "scriptId":"u54"},
    "1ab2057381bf4d179d9c3247b4aefbcb":{
      "scriptId":"u55"},
    "c78f2f88c470408a93be332987d9cc5d":{
      "scriptId":"u56"},
    "9a37efb03e3b4d698a1c5b51c508e486":{
      "scriptId":"u57"},
    "464914a244754629a2a583a2f98c055e":{
      "scriptId":"u58"},
    "6cc350c9fec04ce1a18a0f07d49ef74c":{
      "scriptId":"u59"},
    "9d97c0c900e649209ce0ee195ce4ff36":{
      "scriptId":"u60"},
    "ef68ead3c3f341c0b7e83e5402a24a0c":{
      "scriptId":"u61"},
    "40ab02056e0d4cef8b354edc017ab9ce":{
      "scriptId":"u62"},
    "f86d2b8499204f9da4c820bf324de499":{
      "scriptId":"u63"},
    "f3c2293e15e34433becd030de7ef39cd":{
      "scriptId":"u64"},
    "c64763bb9a664d18be85c1e685929957":{
      "scriptId":"u65"},
    "a5a2681dc75846a4a80a9dcce1cc0ac0":{
      "scriptId":"u66"},
    "c34404f34ef64f5ca471e11ad5dd3fd8":{
      "scriptId":"u67"},
    "a2f6e27403654ee6906acc82f778c5fe":{
      "scriptId":"u68"},
    "164ed4f0ec3d4b888910e5257c741553":{
      "scriptId":"u69"},
    "0917162059e94e9c8f803d687a876993":{
      "scriptId":"u70"},
    "d975540d0d3740c3af45d42abdd8d918":{
      "scriptId":"u71"},
    "baab3bbca28e4be28871166540f7f362":{
      "scriptId":"u72"},
    "2380a80482f74c798bb0a15bde87c09c":{
      "scriptId":"u73"},
    "fe7971727bc84b1da59c4a0f6619cddd":{
      "scriptId":"u74"},
    "af7d65a85b634a4191f5fd771f06e358":{
      "scriptId":"u75"},
    "b6778e02625347f487c9395e4fe26134":{
      "scriptId":"u76"},
    "cb937d8c1e9841d5851aed068189dfff":{
      "scriptId":"u77"},
    "e176373882774df9821885da1397c229":{
      "scriptId":"u78"},
    "b8655601d6db47d290ca93e76f2ff20a":{
      "scriptId":"u79"},
    "41fb5d36632544759fd980669ca848c0":{
      "scriptId":"u80"},
    "cdc5a4c83971496eb3cd55a18e4aafd2":{
      "scriptId":"u81"},
    "2375a8536a2349e4b279f5b285446ae7":{
      "scriptId":"u82"},
    "ba3f5c9e11dd476db13b64b7fbf81126":{
      "scriptId":"u83"},
    "e54dce9a082c41f1aefaba7f136de0e8":{
      "scriptId":"u84"},
    "ea6a2006e8e4420d83a446bdcd936c62":{
      "scriptId":"u85"},
    "1d9b79159ab9413c9c610da4295a33d6":{
      "scriptId":"u86"},
    "142fa9937e974277a8e46b8518f57a21":{
      "scriptId":"u87"},
    "ac96c74a5607442eab2708f6a26f3b88":{
      "scriptId":"u88"},
    "d88064a0a279487f85ff6f680641816a":{
      "scriptId":"u89"},
    "48ac2b3c39be446f92440917ea54f135":{
      "scriptId":"u90"},
    "4eb2ba79887b4cedbe6f2431319f435d":{
      "scriptId":"u91"},
    "add4efae56cb44d7addfe75ea2d0b0f0":{
      "scriptId":"u92"},
    "0b124dd60d474aae92f3f708f9419b59":{
      "scriptId":"u93"},
    "7dfcb1b8fc944a8ca13676d9bf4fb211":{
      "scriptId":"u94"},
    "bb2f3d26c0094cdc8001e2470e65abb6":{
      "scriptId":"u95"},
    "96b64967c06e4fcfa579930308dd8f7f":{
      "scriptId":"u96"},
    "1340cbcbc7b84ef08515e0f006388065":{
      "scriptId":"u97"},
    "33a8db434fa14d27b8076b64f1ceb36f":{
      "scriptId":"u98"},
    "952c12a0dd334a56997684d15ef1ffd7":{
      "scriptId":"u99"},
    "b1639c0c159840ffb7966b64ff5e5d0f":{
      "scriptId":"u100"},
    "551337023b2d4bf58096f27f62ee80dc":{
      "scriptId":"u101"},
    "45e3e87392c7452e9e5cb180f0f48ff5":{
      "scriptId":"u102"},
    "7791fe4d1cbb420a9f5ae1d86fb5744f":{
      "scriptId":"u103"},
    "f7e9db20557f407dbbce927921f29ab8":{
      "scriptId":"u104"}}});