$axure.loadCurrentPage({
  "url":"应用管理-无.html",
  "generationDate":new Date(1487728187156.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"afdf57783b72424abb2492a1ee6fd509",
    "type":"Axure:Page",
    "name":"应用管理-无",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"db75f6a689f1487c827b0cc14e1a5850",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6e03aba969a64804a7fa4490ab766812"},
{
          "id":"26ac9c4162424cbf8945b9f0a18324a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":99},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfcc0f0865524d3ca4992646802ec90b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":99},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u17.png"}},
{
          "id":"47a6b6ad519841d79231632ad4b60dd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":138},
            "size":{
              "width":200,
              "height":421}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34f6fccc8607406790f90b0b32ee6eeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":138},
                "size":{
                  "width":200,
                  "height":421}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u19.png"}},
{
          "id":"34c37085b7524f1db4a9020117f52cd2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":138},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0037b8126b9e4ecbba1b7860645bb3cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":138},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 个人中心-基本信息",
                      "target":{
                        "targetType":"page",
                        "url":"个人中心-基本信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心-基本信息/u29.png"}},
{
          "id":"def0dad0cfc74b7082285faae05ec4ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":179},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cb478d7d16742019c991a5694a1e231",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":179},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u17.png"}},
{
          "id":"2433b33a86b44cd0a7e92207d5468291",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":220,
              "y":218},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abb869c13a27431bbcf19b0211452dc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":220,
                  "y":218},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 应用管理-有",
                      "target":{
                        "targetType":"page",
                        "url":"应用管理-有.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心-基本信息/u21.png"}},
{
          "id":"0f14cea3ebc141188f699fddb07630aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "location":{
              "x":1210,
              "y":302},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e280418c8f134cdc981a55cccd615392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "location":{
                  "x":1210,
                  "y":302},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 创建应用",
                      "target":{
                        "targetType":"page",
                        "url":"创建应用.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/应用管理-无/u27.png"}},
{
          "id":"73dc2cd675c84a07bcc4bb1755f94a2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":160},
            "size":{
              "width":820,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb2baf7dbf6f42f880e5d5ba84adc040",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":160},
                "size":{
                  "width":820,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/应用管理-无/u29.png"}}]}},
  "masters":{
    "6e03aba969a64804a7fa4490ab766812":{
      "packageId":"6e03aba969a64804a7fa4490ab766812",
      "type":"Axure:Master",
      "name":"banner",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a379bbcedb33484ebee107fd9c00378e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1370,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"623ed66a746d41b3a92930eccc112eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1370,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u1.png"}},
{
            "id":"7e02905f180d444e82bf7a5e5f714ed2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":146,
                "y":40},
              "size":{
                "width":114,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23469a3e4ec040068e7550ebfc87d3fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":146,
                    "y":40},
                  "size":{
                    "width":114,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b922b24f0c8c43d79cb58b86621900a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":25},
              "size":{
                "width":100,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97728730fc9e442e987885d0bedd7b6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":25},
                  "size":{
                    "width":100,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u5.png"}},
{
            "id":"0980d651269a4ee0996ac0911a37f74d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":360,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0890f7341e6a49ddb31eb81acdbadf59",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":360,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-登陆后",
                        "target":{
                          "targetType":"page",
                          "url":"首页-登陆后.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"b85b3c40a072433a8432159a76f4d82c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":510,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"40321ea5c398434fbfe7b32670a82628",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":510,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 应用管理-无",
                        "target":{
                          "targetType":"page",
                          "url":"应用管理-无.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"65cb50f858734024be55b79cf7647867",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":660,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"950e973e89a14b04b6aeb8769318250d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":660,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c5c2818163684e16951f2f96bb2e461e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":810,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f5a0cb72b6d94ce992936281e7e57efa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":810,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c80392740b724ca4a02d640db27ef42d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1176,
                "y":34},
              "size":{
                "width":94,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"574479846c4b4024bf9f32b14cbbf5ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1176,
                    "y":34},
                  "size":{
                    "width":94,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心-基本信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心-基本信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "db75f6a689f1487c827b0cc14e1a5850":{
      "scriptId":"u0",
      "a379bbcedb33484ebee107fd9c00378e":{
        "scriptId":"u1"},
      "623ed66a746d41b3a92930eccc112eeb":{
        "scriptId":"u2"},
      "7e02905f180d444e82bf7a5e5f714ed2":{
        "scriptId":"u3"},
      "23469a3e4ec040068e7550ebfc87d3fd":{
        "scriptId":"u4"},
      "b922b24f0c8c43d79cb58b86621900a2":{
        "scriptId":"u5"},
      "97728730fc9e442e987885d0bedd7b6d":{
        "scriptId":"u6"},
      "0980d651269a4ee0996ac0911a37f74d":{
        "scriptId":"u7"},
      "0890f7341e6a49ddb31eb81acdbadf59":{
        "scriptId":"u8"},
      "b85b3c40a072433a8432159a76f4d82c":{
        "scriptId":"u9"},
      "40321ea5c398434fbfe7b32670a82628":{
        "scriptId":"u10"},
      "65cb50f858734024be55b79cf7647867":{
        "scriptId":"u11"},
      "950e973e89a14b04b6aeb8769318250d":{
        "scriptId":"u12"},
      "c5c2818163684e16951f2f96bb2e461e":{
        "scriptId":"u13"},
      "f5a0cb72b6d94ce992936281e7e57efa":{
        "scriptId":"u14"},
      "c80392740b724ca4a02d640db27ef42d":{
        "scriptId":"u15"},
      "574479846c4b4024bf9f32b14cbbf5ea":{
        "scriptId":"u16"}},
    "26ac9c4162424cbf8945b9f0a18324a7":{
      "scriptId":"u17"},
    "cfcc0f0865524d3ca4992646802ec90b":{
      "scriptId":"u18"},
    "47a6b6ad519841d79231632ad4b60dd7":{
      "scriptId":"u19"},
    "34f6fccc8607406790f90b0b32ee6eeb":{
      "scriptId":"u20"},
    "34c37085b7524f1db4a9020117f52cd2":{
      "scriptId":"u21"},
    "0037b8126b9e4ecbba1b7860645bb3cc":{
      "scriptId":"u22"},
    "def0dad0cfc74b7082285faae05ec4ad":{
      "scriptId":"u23"},
    "4cb478d7d16742019c991a5694a1e231":{
      "scriptId":"u24"},
    "2433b33a86b44cd0a7e92207d5468291":{
      "scriptId":"u25"},
    "abb869c13a27431bbcf19b0211452dc7":{
      "scriptId":"u26"},
    "0f14cea3ebc141188f699fddb07630aa":{
      "scriptId":"u27"},
    "e280418c8f134cdc981a55cccd615392":{
      "scriptId":"u28"},
    "73dc2cd675c84a07bcc4bb1755f94a2a":{
      "scriptId":"u29"},
    "eb2baf7dbf6f42f880e5d5ba84adc040":{
      "scriptId":"u30"}}});