$axure.loadCurrentPage({
  "url":"接入指南审核.html",
  "generationDate":new Date(1488533172835.01),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0601cce89af84629a790c34736e7224f",
    "type":"Axure:Page",
    "name":"接入指南审核",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bbc92ca1d79842168ce0654393f87e65",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"7a02efa0d5604338a3be75f38bcf2b86"},
{
          "id":"b0f4f7c92ba94eba9a958731eb092350",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":87},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4d720c32b9b4d46a329ff40eefd910e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":87},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"26f8148df31d485e8fc02e0224822c63",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":447,
              "y":83},
            "size":{
              "width":151,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2d46a8cf46a24f64ae8fd55caba9409f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":954,
              "y":83},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"90c7690db469466f8ebaffdbc9d8eeed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":359},
            "size":{
              "width":340,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d33d2e9a6da446798dc647409449c24e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":359},
                "size":{
                  "width":340,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u82.png"}},
{
          "id":"d880db65f8004d79b7bc290ad7553307",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":340},
            "size":{
              "width":340,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1240737ecc2c493da7e6519e0d5c8f27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":340},
                "size":{
                  "width":340,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u84.png"}},
{
          "id":"95b0154f423f4f80bb60adb2ae22f97d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":400},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d93e5250eee249ca93ce4a212aea3390",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":400},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb5c09d59ebd422dbe0bcb071328a0f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":391},
            "size":{
              "width":70,
              "height":40},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1b8f270254640f0be5dd9fda004f344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":391},
                "size":{
                  "width":70,
                  "height":40},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/api提供者认证审核/u88.png"}},
{
          "id":"b98ab8cc79a043acac729640901a32af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":391},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ff277e2ba48408da23400d89cb15d20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":565,
                  "y":391},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u88.png"}},
{
          "id":"5e4740c0966d43e5b2dd3e93048e6296",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":452},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f08516b2cd43548b725a0a923b1a2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":452},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1f310c38eed4c5ba47611490fa0b838",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":448},
            "size":{
              "width":220,
              "height":62}},
          "adaptiveStyles":{
}},
{
          "id":"0a4c38bb172d458bb8fe2c2523fe529d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":540},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"48cf45f94825443e9018061173d909e8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":540},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"c7492b7590b94c1a8225bb96533af2d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":640,
              "y":87},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a042a2bcc1be41fd839f34cb17604663",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":640,
                  "y":87},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"013aa4f4bf864577a15c5894bb2674ac",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":724,
              "y":84},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"b7fd71b149c344b48f587e2398646d40",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":160},
            "size":{
              "width":750,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"deca3d1ad21b4400be801c51703ff3bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63681ac01a0843758dae686236dd481c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u42.png"}},
{
              "id":"dafc859b53904d1b96d0b500e1136b53",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c55d208c1d2540e3a6c5ab6a75f9e312",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u42.png"}},
{
              "id":"505f73fcce1e418b82dac13d95a3afcc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":30},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe64f66d314044be86c3c8603a5b331c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":108,
                      "y":30},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 接入指南列表",
                          "target":{
                            "targetType":"page",
                            "url":"接入指南列表.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/功能分组/u15.png"}},
{
              "id":"84f8bfbe631348c6abb8c611972e5e09",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":60},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"11f145107d334eb5bf13228525e44fdb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":108,
                      "y":60},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u15.png"}},
{
              "id":"e96ea5aba8e84c36802f381b2ae5ba16",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":555,
                  "y":30},
                "size":{
                  "width":195,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"991ce5c3db2d4a5aa031bdd2a3e3fee6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":555,
                      "y":30},
                    "size":{
                      "width":195,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u48.png"}},
{
              "id":"6bffe69cc48042ae9175a73b8ddbd0ce",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":555,
                  "y":60},
                "size":{
                  "width":195,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b539a8b4dd70441c967bc8a2ac50e4c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":555,
                      "y":60},
                    "size":{
                      "width":195,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u48.png"}},
{
              "id":"a61d54eebc964a00a3931d936e2e9ad2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":333,
                  "y":30},
                "size":{
                  "width":222,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"178ed97214e44ec494cfccc773d8a496",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":333,
                      "y":30},
                    "size":{
                      "width":222,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u46.png"}},
{
              "id":"af773747cad842d3b38dcc7e453fe6db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":333,
                  "y":60},
                "size":{
                  "width":222,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"097195f9ffa44c72b08fe5a87127b3b0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":333,
                      "y":60},
                    "size":{
                      "width":222,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u46.png"}},
{
              "id":"f7de93e2b0244d65b16ff7671418c6a6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"59570487696544b48dbf4e85df346424",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u42.png"}},
{
              "id":"8e954ea4f46048d09b60a0ce7f47c78e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":108,
                  "y":0},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8b9397fc108a4f1f93b68e8734206901",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":108,
                      "y":0},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u15.png"}},
{
              "id":"37f6d45461254f2f8f421c92bdf4f8b6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":333,
                  "y":0},
                "size":{
                  "width":222,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"59189ee2641547f3a47991f6028b7e04",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":333,
                      "y":0},
                    "size":{
                      "width":222,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u46.png"}},
{
              "id":"290fca4548374031b01a1ef367d7ac0f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":555,
                  "y":0},
                "size":{
                  "width":195,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e9b41b278d6a45309c706b59c2d18768",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":555,
                      "y":0},
                    "size":{
                      "width":195,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u48.png"}},
{
              "id":"711f0c4580474b21b02cb648ac0d07b1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"62d04d8b1a2647739c1d930bdb8b7a2d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u74.png"}},
{
              "id":"4eb5e61c145a45c895c9b477d95524bf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":120},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aa9f033e0dc34d4abbf132d75a42434b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":108,
                      "y":120},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u55.png"}},
{
              "id":"84244d2b3d274f3c92fade85eb9b9e81",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":333,
                  "y":120},
                "size":{
                  "width":222,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"989e77d342ed4c29aab2217e73c7d119",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":333,
                      "y":120},
                    "size":{
                      "width":222,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u78.png"}},
{
              "id":"796434f5de4f4c7aba66cdc5f3100d9e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":555,
                  "y":120},
                "size":{
                  "width":195,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18d593443d8c4868b60e071559013669",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":555,
                      "y":120},
                    "size":{
                      "width":195,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u80.png"}},
{
              "id":"19b1a1eb306247758f73bdc595c4d2c0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e394a2a39d7048fd8a58728bcbf57279",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u42.png"}},
{
              "id":"53d869b6e37146c9ab3e76a9ef2c55d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":108,
                  "y":90},
                "size":{
                  "width":225,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f112b444b2ab4ccd94ecf345d04ec788",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":108,
                      "y":90},
                    "size":{
                      "width":225,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组/u15.png"}},
{
              "id":"a6967584af214388b25f5d23c8ac7491",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":333,
                  "y":90},
                "size":{
                  "width":222,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"400018ac631c4f1dba6a04129987727b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":333,
                      "y":90},
                    "size":{
                      "width":222,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u46.png"}},
{
              "id":"ee7f17f2fe1d4428ac695c409ef63512",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":555,
                  "y":90},
                "size":{
                  "width":195,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4512de2a47584e55a39a5994e49a28c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":555,
                      "y":90},
                    "size":{
                      "width":195,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接入指南审核/u48.png"}}]},
{
          "id":"836e5c28030049718b32ebb7578f2e68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":140,
              "y":146},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44ebff4796534ebe9eea5bbfa29e284c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":140,
                  "y":146},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 接入指南审核",
                      "target":{
                        "targetType":"page",
                        "url":"接入指南审核.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/开发者认证审核/u19.png"}},
{
          "id":"d3d2456769b84398b9cc55bc845c1330",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":815,
              "y":350}},
          "adaptiveStyles":{
},
          "masterId":"73a894822cb04a979991d5c2fe28869c"}]}},
  "masters":{
    "7a02efa0d5604338a3be75f38bcf2b86":{
      "packageId":"7a02efa0d5604338a3be75f38bcf2b86",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"03bd36ac64d041918c6dc3aa6374751a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df66acca03bf499aa135bbcb6227b967",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"6b692c7b87a3402b9ce9a61959969a10",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0099FF,
                "opacity":1},
              "location":{
                "x":59,
                "y":18},
              "size":{
                "width":241,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c6cdd631e4d43428f7d756760855ef4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0099FF,
                    "opacity":1},
                  "location":{
                    "x":59,
                    "y":18},
                  "size":{
                    "width":241,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ff8b4a4f418f41888cc0cac89e0b6cc6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":59},
              "size":{
                "width":200,
                "height":421}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"95d3026929da487595c46ec0c6ac3c87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":59},
                  "size":{
                    "width":200,
                    "height":421}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u5.png"}},
{
            "id":"7afee1299b2b48a8a6be957ef89fe2af",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":59},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc8fa126bf8e4cc6a842e757b7b28f3f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":59},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API提供者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"api提供者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"b796130b619e4ad2b19a50e713cbbd40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":88},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b0b3db928fd4bdc8935f7e7b7748902",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":88},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 开发者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"开发者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"ef5b7a53388f4425b08610aa93a79189",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":175},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d9fbdea8ac94145a0e1dac4db9bfff5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":175},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 应用上线审核",
                        "target":{
                          "targetType":"page",
                          "url":"应用上线审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"a13a6ce77356497b9dcac880c9acd548",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":117},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4416e82b29c84e7cb040527f4c8a5b03",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":117},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API接口审核",
                        "target":{
                          "targetType":"page",
                          "url":"api接口审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"01bcdd63c23f4cdd8d8a524437ac1102",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":146},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82d50f80e0ba46fc820d9a4ca86db1f1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":146},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 接入指南审核",
                        "target":{
                          "targetType":"page",
                          "url":"接入指南审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"eabd7026a24944e1a21cd8e4f0df4689",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":204},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7cd7f6c343744aaf975767f39e9ee417",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":204},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 申请功能分组申请",
                        "target":{
                          "targetType":"page",
                          "url":"申请功能分组申请.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}}]}},
    "73a894822cb04a979991d5c2fe28869c":{
      "packageId":"73a894822cb04a979991d5c2fe28869c",
      "type":"Axure:Master",
      "name":"翻页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"10d52bd26dc1429d999b03125a9c30cd",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFF009DD9},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b19aa526c55b43a09d0a1f52cdf59b18",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFF009DD9},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/开发者认证审核/u108.png"}},
{
            "id":"f26fa46f0dbc4366a6042205121f2c66",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":39,
                "y":0},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"72a52d57282b4c4c80e48c143aecd9af",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":39,
                    "y":0},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/开发者认证审核/u110.png"}},
{
            "id":"14683dc145f9469990d88e014b997a79",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":77,
                "y":0},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c6f1500a0a1d464cb746d76763b7800e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":77,
                    "y":0},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/开发者认证审核/u110.png"}},
{
            "id":"89b2005568934e69a9300a402254f159",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":154,
                "y":10},
              "size":{
                "width":116,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c2eef9ed5dc14494acf888eb6c387fe9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":154,
                    "y":10},
                  "size":{
                    "width":116,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"3b9121491e514f7a847a64d546b1ae1f",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "location":{
                "x":192,
                "y":2.5},
              "size":{
                "width":50,
                "height":25}},
            "adaptiveStyles":{
}},
{
            "id":"ec6df84c54834a539dede8852c0eb792",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":116,
                "y":0},
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"da38fc0fa4884178a9be73b9e6074536",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":116,
                    "y":0},
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/开发者认证审核/u110.png"}}]}}},
  "objectPaths":{
    "bbc92ca1d79842168ce0654393f87e65":{
      "scriptId":"u0",
      "03bd36ac64d041918c6dc3aa6374751a":{
        "scriptId":"u1"},
      "df66acca03bf499aa135bbcb6227b967":{
        "scriptId":"u2"},
      "6b692c7b87a3402b9ce9a61959969a10":{
        "scriptId":"u3"},
      "8c6cdd631e4d43428f7d756760855ef4":{
        "scriptId":"u4"},
      "ff8b4a4f418f41888cc0cac89e0b6cc6":{
        "scriptId":"u5"},
      "95d3026929da487595c46ec0c6ac3c87":{
        "scriptId":"u6"},
      "7afee1299b2b48a8a6be957ef89fe2af":{
        "scriptId":"u7"},
      "cc8fa126bf8e4cc6a842e757b7b28f3f":{
        "scriptId":"u8"},
      "b796130b619e4ad2b19a50e713cbbd40":{
        "scriptId":"u9"},
      "6b0b3db928fd4bdc8935f7e7b7748902":{
        "scriptId":"u10"},
      "ef5b7a53388f4425b08610aa93a79189":{
        "scriptId":"u11"},
      "5d9fbdea8ac94145a0e1dac4db9bfff5":{
        "scriptId":"u12"},
      "a13a6ce77356497b9dcac880c9acd548":{
        "scriptId":"u13"},
      "4416e82b29c84e7cb040527f4c8a5b03":{
        "scriptId":"u14"},
      "01bcdd63c23f4cdd8d8a524437ac1102":{
        "scriptId":"u15"},
      "82d50f80e0ba46fc820d9a4ca86db1f1":{
        "scriptId":"u16"},
      "eabd7026a24944e1a21cd8e4f0df4689":{
        "scriptId":"u17"},
      "7cd7f6c343744aaf975767f39e9ee417":{
        "scriptId":"u18"}},
    "b0f4f7c92ba94eba9a958731eb092350":{
      "scriptId":"u19"},
    "a4d720c32b9b4d46a329ff40eefd910e":{
      "scriptId":"u20"},
    "26f8148df31d485e8fc02e0224822c63":{
      "scriptId":"u21"},
    "2d46a8cf46a24f64ae8fd55caba9409f":{
      "scriptId":"u22"},
    "90c7690db469466f8ebaffdbc9d8eeed":{
      "scriptId":"u23"},
    "d33d2e9a6da446798dc647409449c24e":{
      "scriptId":"u24"},
    "d880db65f8004d79b7bc290ad7553307":{
      "scriptId":"u25"},
    "1240737ecc2c493da7e6519e0d5c8f27":{
      "scriptId":"u26"},
    "95b0154f423f4f80bb60adb2ae22f97d":{
      "scriptId":"u27"},
    "d93e5250eee249ca93ce4a212aea3390":{
      "scriptId":"u28"},
    "fb5c09d59ebd422dbe0bcb071328a0f0":{
      "scriptId":"u29"},
    "e1b8f270254640f0be5dd9fda004f344":{
      "scriptId":"u30"},
    "b98ab8cc79a043acac729640901a32af":{
      "scriptId":"u31"},
    "5ff277e2ba48408da23400d89cb15d20":{
      "scriptId":"u32"},
    "5e4740c0966d43e5b2dd3e93048e6296":{
      "scriptId":"u33"},
    "a4f08516b2cd43548b725a0a923b1a2d":{
      "scriptId":"u34"},
    "a1f310c38eed4c5ba47611490fa0b838":{
      "scriptId":"u35"},
    "0a4c38bb172d458bb8fe2c2523fe529d":{
      "scriptId":"u36"},
    "48cf45f94825443e9018061173d909e8":{
      "scriptId":"u37"},
    "c7492b7590b94c1a8225bb96533af2d8":{
      "scriptId":"u38"},
    "a042a2bcc1be41fd839f34cb17604663":{
      "scriptId":"u39"},
    "013aa4f4bf864577a15c5894bb2674ac":{
      "scriptId":"u40"},
    "b7fd71b149c344b48f587e2398646d40":{
      "scriptId":"u41"},
    "f7de93e2b0244d65b16ff7671418c6a6":{
      "scriptId":"u42"},
    "59570487696544b48dbf4e85df346424":{
      "scriptId":"u43"},
    "8e954ea4f46048d09b60a0ce7f47c78e":{
      "scriptId":"u44"},
    "8b9397fc108a4f1f93b68e8734206901":{
      "scriptId":"u45"},
    "37f6d45461254f2f8f421c92bdf4f8b6":{
      "scriptId":"u46"},
    "59189ee2641547f3a47991f6028b7e04":{
      "scriptId":"u47"},
    "290fca4548374031b01a1ef367d7ac0f":{
      "scriptId":"u48"},
    "e9b41b278d6a45309c706b59c2d18768":{
      "scriptId":"u49"},
    "deca3d1ad21b4400be801c51703ff3bf":{
      "scriptId":"u50"},
    "63681ac01a0843758dae686236dd481c":{
      "scriptId":"u51"},
    "505f73fcce1e418b82dac13d95a3afcc":{
      "scriptId":"u52"},
    "fe64f66d314044be86c3c8603a5b331c":{
      "scriptId":"u53"},
    "a61d54eebc964a00a3931d936e2e9ad2":{
      "scriptId":"u54"},
    "178ed97214e44ec494cfccc773d8a496":{
      "scriptId":"u55"},
    "e96ea5aba8e84c36802f381b2ae5ba16":{
      "scriptId":"u56"},
    "991ce5c3db2d4a5aa031bdd2a3e3fee6":{
      "scriptId":"u57"},
    "dafc859b53904d1b96d0b500e1136b53":{
      "scriptId":"u58"},
    "c55d208c1d2540e3a6c5ab6a75f9e312":{
      "scriptId":"u59"},
    "84f8bfbe631348c6abb8c611972e5e09":{
      "scriptId":"u60"},
    "11f145107d334eb5bf13228525e44fdb":{
      "scriptId":"u61"},
    "af773747cad842d3b38dcc7e453fe6db":{
      "scriptId":"u62"},
    "097195f9ffa44c72b08fe5a87127b3b0":{
      "scriptId":"u63"},
    "6bffe69cc48042ae9175a73b8ddbd0ce":{
      "scriptId":"u64"},
    "b539a8b4dd70441c967bc8a2ac50e4c4":{
      "scriptId":"u65"},
    "19b1a1eb306247758f73bdc595c4d2c0":{
      "scriptId":"u66"},
    "e394a2a39d7048fd8a58728bcbf57279":{
      "scriptId":"u67"},
    "53d869b6e37146c9ab3e76a9ef2c55d1":{
      "scriptId":"u68"},
    "f112b444b2ab4ccd94ecf345d04ec788":{
      "scriptId":"u69"},
    "a6967584af214388b25f5d23c8ac7491":{
      "scriptId":"u70"},
    "400018ac631c4f1dba6a04129987727b":{
      "scriptId":"u71"},
    "ee7f17f2fe1d4428ac695c409ef63512":{
      "scriptId":"u72"},
    "4512de2a47584e55a39a5994e49a28c9":{
      "scriptId":"u73"},
    "711f0c4580474b21b02cb648ac0d07b1":{
      "scriptId":"u74"},
    "62d04d8b1a2647739c1d930bdb8b7a2d":{
      "scriptId":"u75"},
    "4eb5e61c145a45c895c9b477d95524bf":{
      "scriptId":"u76"},
    "aa9f033e0dc34d4abbf132d75a42434b":{
      "scriptId":"u77"},
    "84244d2b3d274f3c92fade85eb9b9e81":{
      "scriptId":"u78"},
    "989e77d342ed4c29aab2217e73c7d119":{
      "scriptId":"u79"},
    "796434f5de4f4c7aba66cdc5f3100d9e":{
      "scriptId":"u80"},
    "18d593443d8c4868b60e071559013669":{
      "scriptId":"u81"},
    "836e5c28030049718b32ebb7578f2e68":{
      "scriptId":"u82"},
    "44ebff4796534ebe9eea5bbfa29e284c":{
      "scriptId":"u83"},
    "d3d2456769b84398b9cc55bc845c1330":{
      "scriptId":"u84",
      "10d52bd26dc1429d999b03125a9c30cd":{
        "scriptId":"u85"},
      "b19aa526c55b43a09d0a1f52cdf59b18":{
        "scriptId":"u86"},
      "f26fa46f0dbc4366a6042205121f2c66":{
        "scriptId":"u87"},
      "72a52d57282b4c4c80e48c143aecd9af":{
        "scriptId":"u88"},
      "14683dc145f9469990d88e014b997a79":{
        "scriptId":"u89"},
      "c6f1500a0a1d464cb746d76763b7800e":{
        "scriptId":"u90"},
      "89b2005568934e69a9300a402254f159":{
        "scriptId":"u91"},
      "c2eef9ed5dc14494acf888eb6c387fe9":{
        "scriptId":"u92"},
      "3b9121491e514f7a847a64d546b1ae1f":{
        "scriptId":"u93"},
      "ec6df84c54834a539dede8852c0eb792":{
        "scriptId":"u94"},
      "da38fc0fa4884178a9be73b9e6074536":{
        "scriptId":"u95"}}}});