$axure.loadCurrentPage({
  "url":"认证信息.html",
  "generationDate":new Date(1487654817812.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7df85e88552245a19adcd8451de6c1e2",
    "type":"Axure:Page",
    "name":"认证信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"605b3404254e4f39b137bac1e96abce9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6e03aba969a64804a7fa4490ab766812"},
{
          "id":"3925dbf4cf3f48eb92b4cfc3d36630e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":99},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05f0e4332fdd4225ac1d6dc4fee5486f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":99},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u17.png"}},
{
          "id":"88bb3142caaa4ddc812198521759be74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":138},
            "size":{
              "width":200,
              "height":421}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab4b0202f74041b3aaf7c9431623c0c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":138},
                "size":{
                  "width":200,
                  "height":421}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u19.png"}},
{
          "id":"f90f15ca9aee472c81746ae4f41c977e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":138},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08a32dcf00b84fc4bdbfcdbd4ce89db8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":138},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u23.png"}},
{
          "id":"bf234902ce434cd19e9210e1aea26775",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":179},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ca29380944444aca751fbc6f2936b3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":179},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u23.png"}},
{
          "id":"836308da1cef4eedae02012779f92bcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF999999},
            "location":{
              "x":220,
              "y":220},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac496093248945599d31e15d80c5b3b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "location":{
                  "x":220,
                  "y":220},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u21.png"}},
{
          "id":"7d2b2d7382664aaa89107af352a65c16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":261},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96e8b893a267434bb779ddb44daef2d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":261},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u17.png"}},
{
          "id":"cd86605087324fc3a32b1f532ecfcd65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":140},
            "size":{
              "width":790,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b2982b5a70d43d6947c1124a0902a96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":140},
                "size":{
                  "width":790,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u29.png"}},
{
          "id":"572da76609834be18e06dbbd92abae2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":168},
            "size":{
              "width":430,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d6c3eb7f8fa49b3a8f6f7862852490a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":168},
                "size":{
                  "width":430,
                  "height":144}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4771bab1d85f404881f2b3db2ab9d03b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":560,
              "y":251},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 提供者认证",
                      "target":{
                        "targetType":"page",
                        "url":"提供者认证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "6e03aba969a64804a7fa4490ab766812":{
      "packageId":"6e03aba969a64804a7fa4490ab766812",
      "type":"Axure:Master",
      "name":"banner",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a379bbcedb33484ebee107fd9c00378e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1370,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"623ed66a746d41b3a92930eccc112eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1370,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u1.png"}},
{
            "id":"7e02905f180d444e82bf7a5e5f714ed2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":146,
                "y":40},
              "size":{
                "width":114,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23469a3e4ec040068e7550ebfc87d3fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":146,
                    "y":40},
                  "size":{
                    "width":114,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b922b24f0c8c43d79cb58b86621900a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":25},
              "size":{
                "width":100,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97728730fc9e442e987885d0bedd7b6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":25},
                  "size":{
                    "width":100,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u5.png"}},
{
            "id":"0980d651269a4ee0996ac0911a37f74d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":360,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0890f7341e6a49ddb31eb81acdbadf59",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":360,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-登陆后",
                        "target":{
                          "targetType":"page",
                          "url":"首页-登陆后.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"b85b3c40a072433a8432159a76f4d82c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":510,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"40321ea5c398434fbfe7b32670a82628",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":510,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 业务中心-未认证",
                        "target":{
                          "targetType":"page",
                          "url":"业务中心-未认证.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"65cb50f858734024be55b79cf7647867",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":660,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"950e973e89a14b04b6aeb8769318250d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":660,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c5c2818163684e16951f2f96bb2e461e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":810,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f5a0cb72b6d94ce992936281e7e57efa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":810,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c80392740b724ca4a02d640db27ef42d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1176,
                "y":34},
              "size":{
                "width":94,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"574479846c4b4024bf9f32b14cbbf5ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1176,
                    "y":34},
                  "size":{
                    "width":94,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "605b3404254e4f39b137bac1e96abce9":{
      "scriptId":"u0",
      "a379bbcedb33484ebee107fd9c00378e":{
        "scriptId":"u1"},
      "623ed66a746d41b3a92930eccc112eeb":{
        "scriptId":"u2"},
      "7e02905f180d444e82bf7a5e5f714ed2":{
        "scriptId":"u3"},
      "23469a3e4ec040068e7550ebfc87d3fd":{
        "scriptId":"u4"},
      "b922b24f0c8c43d79cb58b86621900a2":{
        "scriptId":"u5"},
      "97728730fc9e442e987885d0bedd7b6d":{
        "scriptId":"u6"},
      "0980d651269a4ee0996ac0911a37f74d":{
        "scriptId":"u7"},
      "0890f7341e6a49ddb31eb81acdbadf59":{
        "scriptId":"u8"},
      "b85b3c40a072433a8432159a76f4d82c":{
        "scriptId":"u9"},
      "40321ea5c398434fbfe7b32670a82628":{
        "scriptId":"u10"},
      "65cb50f858734024be55b79cf7647867":{
        "scriptId":"u11"},
      "950e973e89a14b04b6aeb8769318250d":{
        "scriptId":"u12"},
      "c5c2818163684e16951f2f96bb2e461e":{
        "scriptId":"u13"},
      "f5a0cb72b6d94ce992936281e7e57efa":{
        "scriptId":"u14"},
      "c80392740b724ca4a02d640db27ef42d":{
        "scriptId":"u15"},
      "574479846c4b4024bf9f32b14cbbf5ea":{
        "scriptId":"u16"}},
    "3925dbf4cf3f48eb92b4cfc3d36630e7":{
      "scriptId":"u17"},
    "05f0e4332fdd4225ac1d6dc4fee5486f":{
      "scriptId":"u18"},
    "88bb3142caaa4ddc812198521759be74":{
      "scriptId":"u19"},
    "ab4b0202f74041b3aaf7c9431623c0c9":{
      "scriptId":"u20"},
    "f90f15ca9aee472c81746ae4f41c977e":{
      "scriptId":"u21"},
    "08a32dcf00b84fc4bdbfcdbd4ce89db8":{
      "scriptId":"u22"},
    "bf234902ce434cd19e9210e1aea26775":{
      "scriptId":"u23"},
    "5ca29380944444aca751fbc6f2936b3f":{
      "scriptId":"u24"},
    "836308da1cef4eedae02012779f92bcd":{
      "scriptId":"u25"},
    "ac496093248945599d31e15d80c5b3b6":{
      "scriptId":"u26"},
    "7d2b2d7382664aaa89107af352a65c16":{
      "scriptId":"u27"},
    "96e8b893a267434bb779ddb44daef2d4":{
      "scriptId":"u28"},
    "cd86605087324fc3a32b1f532ecfcd65":{
      "scriptId":"u29"},
    "5b2982b5a70d43d6947c1124a0902a96":{
      "scriptId":"u30"},
    "572da76609834be18e06dbbd92abae2e":{
      "scriptId":"u31"},
    "5d6c3eb7f8fa49b3a8f6f7862852490a":{
      "scriptId":"u32"},
    "4771bab1d85f404881f2b3db2ab9d03b":{
      "scriptId":"u33"}}});