$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1488425877593.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"223b398b5a7f4b9f85daee436988c84a",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6eb94fd4afb443d7a0066a34624beb91",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":170},
            "size":{
              "width":350,
              "height":380}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59661890c54347db85a5a77207cc68de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":170},
                "size":{
                  "width":350,
                  "height":380}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"eb665d21106c48c393ccc4086eaef374",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":190},
            "size":{
              "width":270,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc91d401e07d413b80ea7fc2c0bafa9a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":190},
                "size":{
                  "width":270,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u2.png"}},
{
          "id":"e0df99271d1241ae929853951a57368f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":305},
            "size":{
              "width":267,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"522388bc72fe4d4ebb6bccd53fa34db2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":355},
            "size":{
              "width":267,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"88f51e84dde34a399397a5b0dbb92823",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":450},
            "size":{
              "width":267,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e55df50d78694706886dc851c2ac5e0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":450},
                "size":{
                  "width":267,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"52b916ff3065465988eea3d2a5167dd6",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":450},
            "size":{
              "width":267,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6f04d6dcba114c1cb2796107470a8a06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":1250,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5014795f3631428588d0c6f397d0b030",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":1250,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u9.png"}},
{
          "id":"75862dff075940f9b86c3f2d3eba37ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":35},
            "size":{
              "width":100,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48e58167e3f64ce78b17ef402e178a0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":35},
                "size":{
                  "width":100,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u11.png"}},
{
          "id":"a35e9b04315a4790800b68843f72a620",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":140,
              "y":61},
            "size":{
              "width":241,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e99e90984aca4debb1567d05ebf26c9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":61},
                "size":{
                  "width":241,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "6eb94fd4afb443d7a0066a34624beb91":{
      "scriptId":"u0"},
    "59661890c54347db85a5a77207cc68de":{
      "scriptId":"u1"},
    "eb665d21106c48c393ccc4086eaef374":{
      "scriptId":"u2"},
    "cc91d401e07d413b80ea7fc2c0bafa9a":{
      "scriptId":"u3"},
    "e0df99271d1241ae929853951a57368f":{
      "scriptId":"u4"},
    "522388bc72fe4d4ebb6bccd53fa34db2":{
      "scriptId":"u5"},
    "88f51e84dde34a399397a5b0dbb92823":{
      "scriptId":"u6"},
    "e55df50d78694706886dc851c2ac5e0e":{
      "scriptId":"u7"},
    "52b916ff3065465988eea3d2a5167dd6":{
      "scriptId":"u8"},
    "6f04d6dcba114c1cb2796107470a8a06":{
      "scriptId":"u9"},
    "5014795f3631428588d0c6f397d0b030":{
      "scriptId":"u10"},
    "75862dff075940f9b86c3f2d3eba37ed":{
      "scriptId":"u11"},
    "48e58167e3f64ce78b17ef402e178a0a":{
      "scriptId":"u12"},
    "a35e9b04315a4790800b68843f72a620":{
      "scriptId":"u13"},
    "e99e90984aca4debb1567d05ebf26c9b":{
      "scriptId":"u14"}}});