$axure.loadCurrentPage({
  "url":"功能分组信息.html",
  "generationDate":new Date(1488181345868.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b4d10095eb6943eb8d7856b872953262",
    "type":"Axure:Page",
    "name":"功能分组信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bc8ef804ebf348e7bd837fe2ba14c7eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":472,
              "y":138},
            "size":{
              "width":838,
              "height":184}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e92534fe97c140188a4d5053486c438b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":472,
                  "y":138},
                "size":{
                  "width":838,
                  "height":184}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eec912b996b44be38e034e657dd88fd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":791,
              "y":580},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"393af386f6324474a23d91fb3dc4ce63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":791,
                  "y":580},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 业务线信息",
                      "target":{
                        "targetType":"page",
                        "url":"业务线信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/业务线信息/u2.png"}},
{
          "id":"82d3eba04a0c4688973acdffd94a13c6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6e03aba969a64804a7fa4490ab766812"},
{
          "id":"f8657fc69fd84532b4b02a5f585d8bf7",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":472,
              "y":308},
            "size":{
              "width":656,
              "height":180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd0f2fc7f0e24875b936a4f82ecfad0c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":76,
                  "y":0},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ce80bcbe2ea84ce59ae82d8866831ee0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":76,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u24.png"}},
{
              "id":"71091d0a9ae54b9e822a14d9300d708f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":76,
                  "y":30},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9e6d45c65c7e441faf7b0f4696a03dcc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":76,
                      "y":30},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 当前窗口 打开 接口文档",
                          "target":{
                            "targetType":"page",
                            "url":"接口文档.html",
                            "includeVariables":true},
                          "linkType":"current"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/功能分组信息/u24.png"}},
{
              "id":"4661c20901f7449d95136a85c15660cb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":76,
                  "y":60},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c95d923f3dd4b3ea0cf2407b646e29c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":76,
                      "y":60},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u24.png"}},
{
              "id":"ba1a479e6f934f91a91a0780916fa905",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":0},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"017619d73e074043b96ce1463def34ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":0},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u26.png"}},
{
              "id":"a9c33208f86440b29361d8baa65656dc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":30},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f1a0f5e621634a699cad5e31523a3f5a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":30},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u26.png"}},
{
              "id":"34fc45a511664b5a875732c33bb1fd33",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":60},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b92ad94dda3a4cad9c49c3930657885d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":60},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u26.png"}},
{
              "id":"9b28c426206a4424b3bac50e8a15b5f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":426,
                  "y":0},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0cedaceebc4541bdab52f75e91f266a8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":426,
                      "y":0},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u30.png"}},
{
              "id":"7a446378d4a9428a92e7a1931308c60d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":426,
                  "y":30},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a7edaede0aed4933a06a7eaa912d9baa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":426,
                      "y":30},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u30.png"}},
{
              "id":"9ad9bad4ad7e4bdbb5a6437e8c33f3ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":426,
                  "y":60},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"769ebb86a4dd42f2b43e8b0a47484b35",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":426,
                      "y":60},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u30.png"}},
{
              "id":"408908f21ed64d6a924e14b5bf67109b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f3bb3f53af834cdcb51aaaf5a9d6de17",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u22.png"}},
{
              "id":"861f2368acb84d508aa4894c35848aa8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c7aaf44d14f04644824906a4ef75a031",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u22.png"}},
{
              "id":"c69ffef728c640308025ef8d6ea70760",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"49bc81d6d320414a8a4240078dcc200b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u22.png"}},
{
              "id":"57a6445022bf49c5b0a9354e5c60fd25",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":90},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d4e214a47074d1eaf0c6c7363cab9b4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":90},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u22.png"}},
{
              "id":"3ff5d3548ea94a5f9a382512571a6c98",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":76,
                  "y":90},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ebeb6dee185d4e18ae378fdd983d8488",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":76,
                      "y":90},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u24.png"}},
{
              "id":"969cabba59bc4ff09b37a11deb7d2279",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":90},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"811ff43e69374181be5efa8545d96c74",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":90},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u26.png"}},
{
              "id":"5af561a0bdeb442881a490cf23b74af1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":426,
                  "y":90},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5a8ee9d7724a4f71ad4802a5ac986c24",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":426,
                      "y":90},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u30.png"}},
{
              "id":"bf686c9b6d294ad7a92e345ae3221c3c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":150},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"297a817d6099427abf7bfe5743bb22e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":150},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u72.png"}},
{
              "id":"e0490b381c5f491b95f14fceaf5c1a0b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":76,
                  "y":150},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"667a8854c9974d7a89d45807f0184d3c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":76,
                      "y":150},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u74.png"}},
{
              "id":"dfdf6d5700dd4a2d8047b23a9f33eec6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":150},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da728bfd103c4040a13f99477880aafa",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":150},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u76.png"}},
{
              "id":"044e4193ae264ff9973d0fefba255ba3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":426,
                  "y":150},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"edc07e22d07e457ba8a383d5aabc528b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":426,
                      "y":150},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u80.png"}},
{
              "id":"8b50b69799574c0dbda6d09a9cca0410",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":120},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d366c01a625e4d81ac62825339dd4690",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":120},
                    "size":{
                      "width":76,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u22.png"}},
{
              "id":"6f3dfe43b1e7472dbea79b10277f93ef",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":76,
                  "y":120},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e8eaf2a9b4be4fe5a17425997add4cea",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":76,
                      "y":120},
                    "size":{
                      "width":130,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u24.png"}},
{
              "id":"4bd4191c65c7453381e96eb065f492af",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":206,
                  "y":120},
                "size":{
                  "width":108,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5dd231b64c554afab15e0b3d72fa1e01",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":206,
                      "y":120},
                    "size":{
                      "width":108,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u26.png"}},
{
              "id":"79026b0dbb4c4b6c92a51153f892a76c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":426,
                  "y":120},
                "size":{
                  "width":230,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e6e789b91cd4e6b85f2bfa524e5c537",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":426,
                      "y":120},
                    "size":{
                      "width":230,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u30.png"}},
{
              "id":"b0bb15fc63b24d048500bba3323f089b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":314,
                  "y":0},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8dac2b1852864768ab86fa8d3288e932",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":314,
                      "y":0},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u28.png"}},
{
              "id":"ff56d4538b90416eacd61c39c9a31e64",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":314,
                  "y":30},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f268fb0f156647faa2b5228e242a510a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":314,
                      "y":30},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u28.png"}},
{
              "id":"70c85c67d9a84da882fa76353f7e987c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":314,
                  "y":60},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f21eef394a6d409489940cd07385161e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":314,
                      "y":60},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u28.png"}},
{
              "id":"49d3c202ddc84f2c8c0c633ceb1da079",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":314,
                  "y":90},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f452207e19c744ca8efa1bb9a6754bc4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":314,
                      "y":90},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u28.png"}},
{
              "id":"988d980b54134340ae211b339beae4df",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":314,
                  "y":120},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a3f44524994e4f2d8136bb1e3c52b434",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":314,
                      "y":120},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u28.png"}},
{
              "id":"d71e03d6a4794d9588cac508b8a5643e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":314,
                  "y":150},
                "size":{
                  "width":112,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c39b018601294ac39ccb3320e0907ff8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":314,
                      "y":150},
                    "size":{
                      "width":112,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能分组信息/u78.png"}}]},
{
          "id":"27de7f64511246b3b03ab0c27b05d0fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":808,
              "y":604},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9f82bea5f59493fa77fb09919d849fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":808,
                  "y":604},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f3bb97bac31444d8bac9ac1f8b84a56d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":1098,
              "y":272},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24bb7851bad3423f8af4288286c858c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":1098,
                  "y":272},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 上传接口",
                      "target":{
                        "targetType":"page",
                        "url":"上传接口.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/业务线信息/u74.png"}},
{
          "id":"f4df95820be24381a6fd7e7f038337f9",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":313},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f358bdf4ab034693b86c0a1cee8a4348",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":313},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0fdbcf922f784ef1ac0af6df5c47988d",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":344},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e5d37a3ae7b4bdc93132a7e35dc668a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":344},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"b66d92ec962b4a06b27901d32faea1d2",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":375},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3511907252d47e89bdf9b3ff4bdb6b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":375},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"0f78e4aea5a1499cbd4ad7ef36d86169",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":405},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01bc9fe3981447f6bab78e581c26a372",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":405},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c5a772707c1c476aab95f15b57cddfea",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":436},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47e13f10530b4ad8a38f381131ba5784",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":436},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"1bc7daf980024869aae18dbdc35d7db1",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":467},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7822f959e4b747b999df704681b18a3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":467},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"9958324a5d7c4a16ae6de9e2aa303ed9",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":498},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ba6c27a124b344ba83b1d8cbaf36b2f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":99},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b9898b172f4e9790fa59bebbfdab3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":99},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u17.png"}},
{
          "id":"f2d903201c204e248c0c24823eaafe5b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":138},
            "size":{
              "width":200,
              "height":421}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"037af54e8a0d44a996d5cfd36c7fc739",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":138},
                "size":{
                  "width":200,
                  "height":421}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u19.png"}},
{
          "id":"112d60185878477e99feee6d0da5cc17",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":138},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4572663d6ae84a95ad5eba7fbc241e2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":138},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务线管理-未认证/u23.png"}}]}},
  "masters":{
    "6e03aba969a64804a7fa4490ab766812":{
      "packageId":"6e03aba969a64804a7fa4490ab766812",
      "type":"Axure:Master",
      "name":"banner",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a379bbcedb33484ebee107fd9c00378e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1370,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"623ed66a746d41b3a92930eccc112eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1370,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u1.png"}},
{
            "id":"7e02905f180d444e82bf7a5e5f714ed2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":146,
                "y":40},
              "size":{
                "width":114,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23469a3e4ec040068e7550ebfc87d3fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":146,
                    "y":40},
                  "size":{
                    "width":114,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b922b24f0c8c43d79cb58b86621900a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":25},
              "size":{
                "width":100,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97728730fc9e442e987885d0bedd7b6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":25},
                  "size":{
                    "width":100,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u5.png"}},
{
            "id":"0980d651269a4ee0996ac0911a37f74d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":360,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0890f7341e6a49ddb31eb81acdbadf59",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":360,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-登陆后",
                        "target":{
                          "targetType":"page",
                          "url":"首页-登陆后.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"65cb50f858734024be55b79cf7647867",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":520,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"950e973e89a14b04b6aeb8769318250d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":520,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c5c2818163684e16951f2f96bb2e461e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":680,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f5a0cb72b6d94ce992936281e7e57efa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":680,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c80392740b724ca4a02d640db27ef42d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1176,
                "y":34},
              "size":{
                "width":94,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"574479846c4b4024bf9f32b14cbbf5ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1176,
                    "y":34},
                  "size":{
                    "width":94,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心-基本信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心-基本信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a60fa91d82174ea3afaf66f60115cb57",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":1170,
                "y":50},
              "size":{
                "width":120,
                "height":40},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"604f3c8191be4df9a58c3e7fb2d464e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1170,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 业务线管理-未认证",
                        "target":{
                          "targetType":"page",
                          "url":"业务线管理-未认证.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u15.png"}}]}}},
  "objectPaths":{
    "bc8ef804ebf348e7bd837fe2ba14c7eb":{
      "scriptId":"u0"},
    "e92534fe97c140188a4d5053486c438b":{
      "scriptId":"u1"},
    "eec912b996b44be38e034e657dd88fd5":{
      "scriptId":"u2"},
    "393af386f6324474a23d91fb3dc4ce63":{
      "scriptId":"u3"},
    "82d3eba04a0c4688973acdffd94a13c6":{
      "scriptId":"u4",
      "a379bbcedb33484ebee107fd9c00378e":{
        "scriptId":"u5"},
      "623ed66a746d41b3a92930eccc112eeb":{
        "scriptId":"u6"},
      "7e02905f180d444e82bf7a5e5f714ed2":{
        "scriptId":"u7"},
      "23469a3e4ec040068e7550ebfc87d3fd":{
        "scriptId":"u8"},
      "b922b24f0c8c43d79cb58b86621900a2":{
        "scriptId":"u9"},
      "97728730fc9e442e987885d0bedd7b6d":{
        "scriptId":"u10"},
      "0980d651269a4ee0996ac0911a37f74d":{
        "scriptId":"u11"},
      "0890f7341e6a49ddb31eb81acdbadf59":{
        "scriptId":"u12"},
      "65cb50f858734024be55b79cf7647867":{
        "scriptId":"u13"},
      "950e973e89a14b04b6aeb8769318250d":{
        "scriptId":"u14"},
      "c5c2818163684e16951f2f96bb2e461e":{
        "scriptId":"u15"},
      "f5a0cb72b6d94ce992936281e7e57efa":{
        "scriptId":"u16"},
      "c80392740b724ca4a02d640db27ef42d":{
        "scriptId":"u17"},
      "574479846c4b4024bf9f32b14cbbf5ea":{
        "scriptId":"u18"},
      "a60fa91d82174ea3afaf66f60115cb57":{
        "scriptId":"u19"},
      "604f3c8191be4df9a58c3e7fb2d464e7":{
        "scriptId":"u20"}},
    "f8657fc69fd84532b4b02a5f585d8bf7":{
      "scriptId":"u21"},
    "408908f21ed64d6a924e14b5bf67109b":{
      "scriptId":"u22"},
    "f3bb3f53af834cdcb51aaaf5a9d6de17":{
      "scriptId":"u23"},
    "dd0f2fc7f0e24875b936a4f82ecfad0c":{
      "scriptId":"u24"},
    "ce80bcbe2ea84ce59ae82d8866831ee0":{
      "scriptId":"u25"},
    "ba1a479e6f934f91a91a0780916fa905":{
      "scriptId":"u26"},
    "017619d73e074043b96ce1463def34ac":{
      "scriptId":"u27"},
    "b0bb15fc63b24d048500bba3323f089b":{
      "scriptId":"u28"},
    "8dac2b1852864768ab86fa8d3288e932":{
      "scriptId":"u29"},
    "9b28c426206a4424b3bac50e8a15b5f4":{
      "scriptId":"u30"},
    "0cedaceebc4541bdab52f75e91f266a8":{
      "scriptId":"u31"},
    "861f2368acb84d508aa4894c35848aa8":{
      "scriptId":"u32"},
    "c7aaf44d14f04644824906a4ef75a031":{
      "scriptId":"u33"},
    "71091d0a9ae54b9e822a14d9300d708f":{
      "scriptId":"u34"},
    "9e6d45c65c7e441faf7b0f4696a03dcc":{
      "scriptId":"u35"},
    "a9c33208f86440b29361d8baa65656dc":{
      "scriptId":"u36"},
    "f1a0f5e621634a699cad5e31523a3f5a":{
      "scriptId":"u37"},
    "ff56d4538b90416eacd61c39c9a31e64":{
      "scriptId":"u38"},
    "f268fb0f156647faa2b5228e242a510a":{
      "scriptId":"u39"},
    "7a446378d4a9428a92e7a1931308c60d":{
      "scriptId":"u40"},
    "a7edaede0aed4933a06a7eaa912d9baa":{
      "scriptId":"u41"},
    "c69ffef728c640308025ef8d6ea70760":{
      "scriptId":"u42"},
    "49bc81d6d320414a8a4240078dcc200b":{
      "scriptId":"u43"},
    "4661c20901f7449d95136a85c15660cb":{
      "scriptId":"u44"},
    "1c95d923f3dd4b3ea0cf2407b646e29c":{
      "scriptId":"u45"},
    "34fc45a511664b5a875732c33bb1fd33":{
      "scriptId":"u46"},
    "b92ad94dda3a4cad9c49c3930657885d":{
      "scriptId":"u47"},
    "70c85c67d9a84da882fa76353f7e987c":{
      "scriptId":"u48"},
    "f21eef394a6d409489940cd07385161e":{
      "scriptId":"u49"},
    "9ad9bad4ad7e4bdbb5a6437e8c33f3ad":{
      "scriptId":"u50"},
    "769ebb86a4dd42f2b43e8b0a47484b35":{
      "scriptId":"u51"},
    "57a6445022bf49c5b0a9354e5c60fd25":{
      "scriptId":"u52"},
    "9d4e214a47074d1eaf0c6c7363cab9b4":{
      "scriptId":"u53"},
    "3ff5d3548ea94a5f9a382512571a6c98":{
      "scriptId":"u54"},
    "ebeb6dee185d4e18ae378fdd983d8488":{
      "scriptId":"u55"},
    "969cabba59bc4ff09b37a11deb7d2279":{
      "scriptId":"u56"},
    "811ff43e69374181be5efa8545d96c74":{
      "scriptId":"u57"},
    "49d3c202ddc84f2c8c0c633ceb1da079":{
      "scriptId":"u58"},
    "f452207e19c744ca8efa1bb9a6754bc4":{
      "scriptId":"u59"},
    "5af561a0bdeb442881a490cf23b74af1":{
      "scriptId":"u60"},
    "5a8ee9d7724a4f71ad4802a5ac986c24":{
      "scriptId":"u61"},
    "8b50b69799574c0dbda6d09a9cca0410":{
      "scriptId":"u62"},
    "d366c01a625e4d81ac62825339dd4690":{
      "scriptId":"u63"},
    "6f3dfe43b1e7472dbea79b10277f93ef":{
      "scriptId":"u64"},
    "e8eaf2a9b4be4fe5a17425997add4cea":{
      "scriptId":"u65"},
    "4bd4191c65c7453381e96eb065f492af":{
      "scriptId":"u66"},
    "5dd231b64c554afab15e0b3d72fa1e01":{
      "scriptId":"u67"},
    "988d980b54134340ae211b339beae4df":{
      "scriptId":"u68"},
    "a3f44524994e4f2d8136bb1e3c52b434":{
      "scriptId":"u69"},
    "79026b0dbb4c4b6c92a51153f892a76c":{
      "scriptId":"u70"},
    "7e6e789b91cd4e6b85f2bfa524e5c537":{
      "scriptId":"u71"},
    "bf686c9b6d294ad7a92e345ae3221c3c":{
      "scriptId":"u72"},
    "297a817d6099427abf7bfe5743bb22e6":{
      "scriptId":"u73"},
    "e0490b381c5f491b95f14fceaf5c1a0b":{
      "scriptId":"u74"},
    "667a8854c9974d7a89d45807f0184d3c":{
      "scriptId":"u75"},
    "dfdf6d5700dd4a2d8047b23a9f33eec6":{
      "scriptId":"u76"},
    "da728bfd103c4040a13f99477880aafa":{
      "scriptId":"u77"},
    "d71e03d6a4794d9588cac508b8a5643e":{
      "scriptId":"u78"},
    "c39b018601294ac39ccb3320e0907ff8":{
      "scriptId":"u79"},
    "044e4193ae264ff9973d0fefba255ba3":{
      "scriptId":"u80"},
    "edc07e22d07e457ba8a383d5aabc528b":{
      "scriptId":"u81"},
    "27de7f64511246b3b03ab0c27b05d0fd":{
      "scriptId":"u82"},
    "a9f82bea5f59493fa77fb09919d849fe":{
      "scriptId":"u83"},
    "f3bb97bac31444d8bac9ac1f8b84a56d":{
      "scriptId":"u84"},
    "24bb7851bad3423f8af4288286c858c3":{
      "scriptId":"u85"},
    "f4df95820be24381a6fd7e7f038337f9":{
      "scriptId":"u86"},
    "f358bdf4ab034693b86c0a1cee8a4348":{
      "scriptId":"u87"},
    "0fdbcf922f784ef1ac0af6df5c47988d":{
      "scriptId":"u88"},
    "7e5d37a3ae7b4bdc93132a7e35dc668a":{
      "scriptId":"u89"},
    "b66d92ec962b4a06b27901d32faea1d2":{
      "scriptId":"u90"},
    "d3511907252d47e89bdf9b3ff4bdb6b7":{
      "scriptId":"u91"},
    "0f78e4aea5a1499cbd4ad7ef36d86169":{
      "scriptId":"u92"},
    "01bc9fe3981447f6bab78e581c26a372":{
      "scriptId":"u93"},
    "c5a772707c1c476aab95f15b57cddfea":{
      "scriptId":"u94"},
    "47e13f10530b4ad8a38f381131ba5784":{
      "scriptId":"u95"},
    "1bc7daf980024869aae18dbdc35d7db1":{
      "scriptId":"u96"},
    "7822f959e4b747b999df704681b18a3f":{
      "scriptId":"u97"},
    "9958324a5d7c4a16ae6de9e2aa303ed9":{
      "scriptId":"u98"},
    "ba6c27a124b344ba83b1d8cbaf36b2f0":{
      "scriptId":"u99"},
    "a7b9898b172f4e9790fa59bebbfdab3e":{
      "scriptId":"u100"},
    "f2d903201c204e248c0c24823eaafe5b":{
      "scriptId":"u101"},
    "037af54e8a0d44a996d5cfd36c7fc739":{
      "scriptId":"u102"},
    "112d60185878477e99feee6d0da5cc17":{
      "scriptId":"u103"},
    "4572663d6ae84a95ad5eba7fbc241e2f":{
      "scriptId":"u104"}}});