$axure.loadCurrentPage({
  "url":"个人中心-基本信息.html",
  "generationDate":new Date(1487728187110.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d000fd25642e41929b05abd3bd4716d8",
    "type":"Axure:Page",
    "name":"个人中心-基本信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"541c248d69fc4ce89dcbd9ea60d46acf",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"6e03aba969a64804a7fa4490ab766812"},
{
          "id":"3d54df77764542f6b73260242838b756",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":99},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0fc7c095705459895ccffc751826429",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":99},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u17.png"}},
{
          "id":"4823d3f70d5c48cfaf08e88ecabb827b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":138},
            "size":{
              "width":200,
              "height":421}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"050183909f8d4a5e844b38a439d71bbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":138},
                "size":{
                  "width":200,
                  "height":421}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u19.png"}},
{
          "id":"01f7b74d65ab48fb81a359847730925a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":220,
              "y":138},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8eb55c65f9f84fd282006eafda132993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":220,
                  "y":138},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u21.png"}},
{
          "id":"873276098e24486e8331b82389e27d84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":179},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"595e353799304f33accd533e90d758c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":179},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心-基本信息/u17.png"}},
{
          "id":"8d630ec286134c64a4280829ecf15996",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":140},
            "size":{
              "width":790,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d455f6c1c1944f6f95df8f80c195e215",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":140},
                "size":{
                  "width":790,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/个人中心-基本信息/u25.png"}},
{
          "id":"1f067c70dfdc4db6b56ad2f1fbbb3b2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":490,
              "y":168},
            "size":{
              "width":430,
              "height":192}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"605ca4822a3846f49da292f79d02ccfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":490,
                  "y":168},
                "size":{
                  "width":430,
                  "height":192}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f2025fc968c64bc18abe595cb8294aff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":218},
            "size":{
              "width":170,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dcc71f1bfbec4221ad646be082ce8e81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":218},
                "size":{
                  "width":170,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 应用管理-无",
                      "target":{
                        "targetType":"page",
                        "url":"应用管理-无.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/个人中心-基本信息/u29.png"}}]}},
  "masters":{
    "6e03aba969a64804a7fa4490ab766812":{
      "packageId":"6e03aba969a64804a7fa4490ab766812",
      "type":"Axure:Master",
      "name":"banner",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"a379bbcedb33484ebee107fd9c00378e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1370,
                "height":100}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"623ed66a746d41b3a92930eccc112eeb",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1370,
                    "height":100}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u1.png"}},
{
            "id":"7e02905f180d444e82bf7a5e5f714ed2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "location":{
                "x":146,
                "y":40},
              "size":{
                "width":114,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"23469a3e4ec040068e7550ebfc87d3fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "location":{
                    "x":146,
                    "y":40},
                  "size":{
                    "width":114,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b922b24f0c8c43d79cb58b86621900a2",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":25},
              "size":{
                "width":100,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"97728730fc9e442e987885d0bedd7b6d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":20,
                    "y":25},
                  "size":{
                    "width":100,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u5.png"}},
{
            "id":"0980d651269a4ee0996ac0911a37f74d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":360,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0890f7341e6a49ddb31eb81acdbadf59",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":360,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 首页-登陆后",
                        "target":{
                          "targetType":"page",
                          "url":"首页-登陆后.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"b85b3c40a072433a8432159a76f4d82c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":510,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"40321ea5c398434fbfe7b32670a82628",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":510,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 应用管理-无",
                        "target":{
                          "targetType":"page",
                          "url":"应用管理-无.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"65cb50f858734024be55b79cf7647867",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":660,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"950e973e89a14b04b6aeb8769318250d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":660,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c5c2818163684e16951f2f96bb2e461e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":810,
                "y":50},
              "size":{
                "width":120,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f5a0cb72b6d94ce992936281e7e57efa",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":810,
                    "y":50},
                  "size":{
                    "width":120,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-未登录/u7.png"}},
{
            "id":"c80392740b724ca4a02d640db27ef42d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "location":{
                "x":1176,
                "y":34},
              "size":{
                "width":94,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"574479846c4b4024bf9f32b14cbbf5ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1176,
                    "y":34},
                  "size":{
                    "width":94,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 个人中心-基本信息",
                        "target":{
                          "targetType":"page",
                          "url":"个人中心-基本信息.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "541c248d69fc4ce89dcbd9ea60d46acf":{
      "scriptId":"u0",
      "a379bbcedb33484ebee107fd9c00378e":{
        "scriptId":"u1"},
      "623ed66a746d41b3a92930eccc112eeb":{
        "scriptId":"u2"},
      "7e02905f180d444e82bf7a5e5f714ed2":{
        "scriptId":"u3"},
      "23469a3e4ec040068e7550ebfc87d3fd":{
        "scriptId":"u4"},
      "b922b24f0c8c43d79cb58b86621900a2":{
        "scriptId":"u5"},
      "97728730fc9e442e987885d0bedd7b6d":{
        "scriptId":"u6"},
      "0980d651269a4ee0996ac0911a37f74d":{
        "scriptId":"u7"},
      "0890f7341e6a49ddb31eb81acdbadf59":{
        "scriptId":"u8"},
      "b85b3c40a072433a8432159a76f4d82c":{
        "scriptId":"u9"},
      "40321ea5c398434fbfe7b32670a82628":{
        "scriptId":"u10"},
      "65cb50f858734024be55b79cf7647867":{
        "scriptId":"u11"},
      "950e973e89a14b04b6aeb8769318250d":{
        "scriptId":"u12"},
      "c5c2818163684e16951f2f96bb2e461e":{
        "scriptId":"u13"},
      "f5a0cb72b6d94ce992936281e7e57efa":{
        "scriptId":"u14"},
      "c80392740b724ca4a02d640db27ef42d":{
        "scriptId":"u15"},
      "574479846c4b4024bf9f32b14cbbf5ea":{
        "scriptId":"u16"}},
    "3d54df77764542f6b73260242838b756":{
      "scriptId":"u17"},
    "e0fc7c095705459895ccffc751826429":{
      "scriptId":"u18"},
    "4823d3f70d5c48cfaf08e88ecabb827b":{
      "scriptId":"u19"},
    "050183909f8d4a5e844b38a439d71bbf":{
      "scriptId":"u20"},
    "01f7b74d65ab48fb81a359847730925a":{
      "scriptId":"u21"},
    "8eb55c65f9f84fd282006eafda132993":{
      "scriptId":"u22"},
    "873276098e24486e8331b82389e27d84":{
      "scriptId":"u23"},
    "595e353799304f33accd533e90d758c9":{
      "scriptId":"u24"},
    "8d630ec286134c64a4280829ecf15996":{
      "scriptId":"u25"},
    "d455f6c1c1944f6f95df8f80c195e215":{
      "scriptId":"u26"},
    "1f067c70dfdc4db6b56ad2f1fbbb3b2e":{
      "scriptId":"u27"},
    "605ca4822a3846f49da292f79d02ccfb":{
      "scriptId":"u28"},
    "f2025fc968c64bc18abe595cb8294aff":{
      "scriptId":"u29"},
    "dcc71f1bfbec4221ad646be082ce8e81":{
      "scriptId":"u30"}}});