$axure.loadCurrentPage({
  "url":"接口信息.html",
  "generationDate":new Date(1488533172721.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3c29b30a29704b46b9ceca611b7808c6",
    "type":"Axure:Page",
    "name":"接口信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ab019cc00bfb47acb0d3c42efa977722",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":80},
            "size":{
              "width":840,
              "height":1005}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08ac3ced9bdd47949ec6c91208542b81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":340,
                  "y":80},
                "size":{
                  "width":840,
                  "height":1005}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c1af6366c7df412fa8df02f02c7b6859",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":668,
              "y":1095},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"facf17fa59134694a1453c452cdfa728",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":668,
                  "y":1095},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/接口信息/u2.png"}},
{
          "id":"916bf774ae394a15864c616567974ca3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":875},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07fdc5632a884e13a821e2f2fcb606b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":875},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6337c6a3e7c74d45b24b7863d395a2f2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":607},
            "size":{
              "width":700,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e22882728d446e29d4b819133d2dedd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"551ed695c29643e5b55ba0bdf0a1dc00",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u7.png"}},
{
              "id":"844bbe9afb784e70bd26e83bf3f55e0a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d94696d26137417688bb133533ddd260",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发者认证审核/u29.png"}},
{
              "id":"f83c84fa35a8464ab3781f36d358f566",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5112cb8ffa8348c99f0b8e3fd397084d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发者认证审核/u29.png"}},
{
              "id":"3755c10b04284083b013a11800b4a639",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21ecb42a9f364504a48ab2f7a852bfde",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u7.png"}},
{
              "id":"3c6d003f286a4cd38ca58e4c83d80281",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d5ef35aa3371419aac86a180fe97937b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u15.png"}},
{
              "id":"f00a6020ea6a4ca4ad67a039a93bba3a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3b3eca4fd079457f89786c404acd139c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u17.png"}},
{
              "id":"ab44f729ed8b4cf7819d71b645d1650e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f12cd0058a284b96a8f6331c09443811",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u19.png"}},
{
              "id":"df2a20cab7e746f49ee588f66cd45f23",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81569d2792f34f3fbdbcf000b6e0b5e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u19.png"}},
{
              "id":"7b7b92865cdd4d748dd8d288413b8369",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12e7da2f2b8649d79d9cc6c7afd5f1c9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u17.png"}},
{
              "id":"034b9581c77647e391800c7a621684d1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25e80dfb608a48ce8a354d696c7a3724",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u25.png"}}]},
{
          "id":"b26fee4b867047d1b1cda3e62011a102",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":732},
            "size":{
              "width":700,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d3ec05c810432ba6ba96cddcac017b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d619fd92bce445eab890d4768692f55d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u7.png"}},
{
              "id":"fc765cc28c5f4155897d4f34e425c944",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"204027eaa5b9445497ca6fbd83d7d487",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发者认证审核/u29.png"}},
{
              "id":"85540565c32f40f79cce026bbf54fbdd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d9d217cd7a6540d8809a4959ab2a145c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发者认证审核/u29.png"}},
{
              "id":"91a7d7a9dfcb4843a0501e0a8799060b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7d0ee0e7cb24251a456f85f8f3f5cb1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u7.png"}},
{
              "id":"48424773baa546d0bbf6be8003017c5e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"bcc43d6bfad641b38752a14022bee0d0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u15.png"}},
{
              "id":"5e9cf4f83e754d0facff7e4006c6f066",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2e16031e514c4a47a1163d9b7d9d0ecc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u17.png"}},
{
              "id":"b5b363f3e62c4cc49d2967c85a0951da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"07639d41c84c4decb9321601898406d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u19.png"}},
{
              "id":"6aeda2b5f59848de8c8fc381090e7ad9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9545e22bcbc14fdbb8157c666bb93242",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u19.png"}},
{
              "id":"4ae2651c87dd4253a6208e0f22361a32",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5108d7b8f367429691316818e760339d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u17.png"}},
{
              "id":"48696739eae244d892973fc3a2f1c439",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6045125df50421d81fc3033a7da5a95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u25.png"}}]},
{
          "id":"230a0a3fbe8c493482c1e20cb4c06c0f",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":861},
            "size":{
              "width":700,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0bc92f4e3024845ae99e58add9ff2eb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b188c99ecbee43bb91021b088ab099d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u7.png"}},
{
              "id":"a25929f01003429e93167bf79111de34",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab93c58f62874eadad28c8d421fef052",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发者认证审核/u29.png"}},
{
              "id":"0c25de447a2b4c51977c9d557af8a233",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1650e8cbe57e48b7b6d170c844eb06b5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/开发者认证审核/u29.png"}},
{
              "id":"c345cecc008e46328c43baecfc2223f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":0},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"975b6fa51fc54600b03b7455c9db3801",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":0},
                    "size":{
                      "width":150,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u7.png"}},
{
              "id":"c86c23c6b9b749b5b019fcf5fd2ebb2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":0},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b283fa93971844339eb27a7b2c663b7b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":0},
                    "size":{
                      "width":200,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u15.png"}},
{
              "id":"f3449a8640e04ce9bfdc2545bec64df2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15a4b8491f2842b5bba096aedae2a0ac",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u17.png"}},
{
              "id":"24b78b62056148d4956724629a2650b3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":150,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"90cfc390b95c41608b1f4cf50f3cc41d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":150,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u19.png"}},
{
              "id":"bc2b21bf005e40e2b6a31bf86dcd036d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":250,
                  "y":30},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"194eff0cc0e949cb8a524c8ca4832d8c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":250,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u19.png"}},
{
              "id":"11ece367f0594dd9b148950057d101fd",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":350,
                  "y":30},
                "size":{
                  "width":150,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"736d38f3d6cb4a01b708170d1e81fa48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":350,
                      "y":30},
                    "size":{
                      "width":150,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u17.png"}},
{
              "id":"a5dcc6f728bf4aeaa48aefccac9a307b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":500,
                  "y":30},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1f49b7e467004911bb577101f33c8fdd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":500,
                      "y":30},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u25.png"}}]},
{
          "id":"71e29acd117241fda7392fd1ad07b15d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":990},
            "size":{
              "width":700,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f03f0f1bb0c4d618d4085c5c943a5c1",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":200,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9d0c9958794641869705c945a15c9bc7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":200,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/api接口审核/u41.png"}},
{
              "id":"20eca1d11f844379a30e1837f4cc3ea8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":500,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"41a87b0fd7f6435eae933fc27e085137",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":500,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u72.png"}},
{
              "id":"d275f1fcc902457286c14146f6d26577",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d8a925c63fe8439e8283e5cd3453d3b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":200,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u74.png"}},
{
              "id":"f10ab4cbbbbb49beb5b231182869171c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":33},
                "size":{
                  "width":500,
                  "height":40}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"43c08cdaaa6a47dd885992d7dcb3df08",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":33},
                    "size":{
                      "width":500,
                      "height":40}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/接口信息/u76.png"}}]},
{
          "id":"190ff44652a7414aa713cfef8c3b7bc6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"7a02efa0d5604338a3be75f38bcf2b86"},
{
          "id":"db50a5edca0a42b190687019a2219cd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":668,
              "y":1158},
            "size":{
              "width":302,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b087f52680048538f4754f1d49e1d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":668,
                  "y":1158},
                "size":{
                  "width":302,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa4f68dba7704716893e8bf0b28f5b39",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":140,
              "y":117},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73fb2b1427f54240baeedd5731eec96f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":140,
                  "y":117},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 API接口审核",
                      "target":{
                        "targetType":"page",
                        "url":"api接口审核.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/开发者认证审核/u19.png"}},
{
          "id":"05975030f9834e44a9cc82b69aa00f35",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":340,
              "y":60},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 业务线信息",
                      "target":{
                        "targetType":"page",
                        "url":"业务线信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"c2536826e7c64da09e59f52b9d3c443c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":60},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 功能分组",
                      "target":{
                        "targetType":"page",
                        "url":"功能分组.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
    "7a02efa0d5604338a3be75f38bcf2b86":{
      "packageId":"7a02efa0d5604338a3be75f38bcf2b86",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"03bd36ac64d041918c6dc3aa6374751a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df66acca03bf499aa135bbcb6227b967",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"6b692c7b87a3402b9ce9a61959969a10",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0099FF,
                "opacity":1},
              "location":{
                "x":59,
                "y":18},
              "size":{
                "width":241,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c6cdd631e4d43428f7d756760855ef4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0099FF,
                    "opacity":1},
                  "location":{
                    "x":59,
                    "y":18},
                  "size":{
                    "width":241,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ff8b4a4f418f41888cc0cac89e0b6cc6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":59},
              "size":{
                "width":200,
                "height":421}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"95d3026929da487595c46ec0c6ac3c87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":59},
                  "size":{
                    "width":200,
                    "height":421}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u5.png"}},
{
            "id":"7afee1299b2b48a8a6be957ef89fe2af",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":59},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc8fa126bf8e4cc6a842e757b7b28f3f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":59},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API提供者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"api提供者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"b796130b619e4ad2b19a50e713cbbd40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":88},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b0b3db928fd4bdc8935f7e7b7748902",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":88},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 开发者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"开发者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"ef5b7a53388f4425b08610aa93a79189",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":175},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d9fbdea8ac94145a0e1dac4db9bfff5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":175},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 应用上线审核",
                        "target":{
                          "targetType":"page",
                          "url":"应用上线审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"a13a6ce77356497b9dcac880c9acd548",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":117},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4416e82b29c84e7cb040527f4c8a5b03",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":117},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API接口审核",
                        "target":{
                          "targetType":"page",
                          "url":"api接口审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"01bcdd63c23f4cdd8d8a524437ac1102",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":146},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82d50f80e0ba46fc820d9a4ca86db1f1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":146},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 接入指南审核",
                        "target":{
                          "targetType":"page",
                          "url":"接入指南审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"eabd7026a24944e1a21cd8e4f0df4689",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":204},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7cd7f6c343744aaf975767f39e9ee417",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":204},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 申请功能分组申请",
                        "target":{
                          "targetType":"page",
                          "url":"申请功能分组申请.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}}]}}},
  "objectPaths":{
    "ab019cc00bfb47acb0d3c42efa977722":{
      "scriptId":"u0"},
    "08ac3ced9bdd47949ec6c91208542b81":{
      "scriptId":"u1"},
    "c1af6366c7df412fa8df02f02c7b6859":{
      "scriptId":"u2"},
    "facf17fa59134694a1453c452cdfa728":{
      "scriptId":"u3"},
    "916bf774ae394a15864c616567974ca3":{
      "scriptId":"u4"},
    "07fdc5632a884e13a821e2f2fcb606b3":{
      "scriptId":"u5"},
    "6337c6a3e7c74d45b24b7863d395a2f2":{
      "scriptId":"u6"},
    "4e22882728d446e29d4b819133d2dedd":{
      "scriptId":"u7"},
    "551ed695c29643e5b55ba0bdf0a1dc00":{
      "scriptId":"u8"},
    "844bbe9afb784e70bd26e83bf3f55e0a":{
      "scriptId":"u9"},
    "d94696d26137417688bb133533ddd260":{
      "scriptId":"u10"},
    "f83c84fa35a8464ab3781f36d358f566":{
      "scriptId":"u11"},
    "5112cb8ffa8348c99f0b8e3fd397084d":{
      "scriptId":"u12"},
    "3755c10b04284083b013a11800b4a639":{
      "scriptId":"u13"},
    "21ecb42a9f364504a48ab2f7a852bfde":{
      "scriptId":"u14"},
    "3c6d003f286a4cd38ca58e4c83d80281":{
      "scriptId":"u15"},
    "d5ef35aa3371419aac86a180fe97937b":{
      "scriptId":"u16"},
    "f00a6020ea6a4ca4ad67a039a93bba3a":{
      "scriptId":"u17"},
    "3b3eca4fd079457f89786c404acd139c":{
      "scriptId":"u18"},
    "ab44f729ed8b4cf7819d71b645d1650e":{
      "scriptId":"u19"},
    "f12cd0058a284b96a8f6331c09443811":{
      "scriptId":"u20"},
    "df2a20cab7e746f49ee588f66cd45f23":{
      "scriptId":"u21"},
    "81569d2792f34f3fbdbcf000b6e0b5e9":{
      "scriptId":"u22"},
    "7b7b92865cdd4d748dd8d288413b8369":{
      "scriptId":"u23"},
    "12e7da2f2b8649d79d9cc6c7afd5f1c9":{
      "scriptId":"u24"},
    "034b9581c77647e391800c7a621684d1":{
      "scriptId":"u25"},
    "25e80dfb608a48ce8a354d696c7a3724":{
      "scriptId":"u26"},
    "b26fee4b867047d1b1cda3e62011a102":{
      "scriptId":"u27"},
    "c4d3ec05c810432ba6ba96cddcac017b":{
      "scriptId":"u28"},
    "d619fd92bce445eab890d4768692f55d":{
      "scriptId":"u29"},
    "fc765cc28c5f4155897d4f34e425c944":{
      "scriptId":"u30"},
    "204027eaa5b9445497ca6fbd83d7d487":{
      "scriptId":"u31"},
    "85540565c32f40f79cce026bbf54fbdd":{
      "scriptId":"u32"},
    "d9d217cd7a6540d8809a4959ab2a145c":{
      "scriptId":"u33"},
    "91a7d7a9dfcb4843a0501e0a8799060b":{
      "scriptId":"u34"},
    "d7d0ee0e7cb24251a456f85f8f3f5cb1":{
      "scriptId":"u35"},
    "48424773baa546d0bbf6be8003017c5e":{
      "scriptId":"u36"},
    "bcc43d6bfad641b38752a14022bee0d0":{
      "scriptId":"u37"},
    "5e9cf4f83e754d0facff7e4006c6f066":{
      "scriptId":"u38"},
    "2e16031e514c4a47a1163d9b7d9d0ecc":{
      "scriptId":"u39"},
    "b5b363f3e62c4cc49d2967c85a0951da":{
      "scriptId":"u40"},
    "07639d41c84c4decb9321601898406d2":{
      "scriptId":"u41"},
    "6aeda2b5f59848de8c8fc381090e7ad9":{
      "scriptId":"u42"},
    "9545e22bcbc14fdbb8157c666bb93242":{
      "scriptId":"u43"},
    "4ae2651c87dd4253a6208e0f22361a32":{
      "scriptId":"u44"},
    "5108d7b8f367429691316818e760339d":{
      "scriptId":"u45"},
    "48696739eae244d892973fc3a2f1c439":{
      "scriptId":"u46"},
    "a6045125df50421d81fc3033a7da5a95":{
      "scriptId":"u47"},
    "230a0a3fbe8c493482c1e20cb4c06c0f":{
      "scriptId":"u48"},
    "b0bc92f4e3024845ae99e58add9ff2eb":{
      "scriptId":"u49"},
    "b188c99ecbee43bb91021b088ab099d8":{
      "scriptId":"u50"},
    "a25929f01003429e93167bf79111de34":{
      "scriptId":"u51"},
    "ab93c58f62874eadad28c8d421fef052":{
      "scriptId":"u52"},
    "0c25de447a2b4c51977c9d557af8a233":{
      "scriptId":"u53"},
    "1650e8cbe57e48b7b6d170c844eb06b5":{
      "scriptId":"u54"},
    "c345cecc008e46328c43baecfc2223f5":{
      "scriptId":"u55"},
    "975b6fa51fc54600b03b7455c9db3801":{
      "scriptId":"u56"},
    "c86c23c6b9b749b5b019fcf5fd2ebb2a":{
      "scriptId":"u57"},
    "b283fa93971844339eb27a7b2c663b7b":{
      "scriptId":"u58"},
    "f3449a8640e04ce9bfdc2545bec64df2":{
      "scriptId":"u59"},
    "15a4b8491f2842b5bba096aedae2a0ac":{
      "scriptId":"u60"},
    "24b78b62056148d4956724629a2650b3":{
      "scriptId":"u61"},
    "90cfc390b95c41608b1f4cf50f3cc41d":{
      "scriptId":"u62"},
    "bc2b21bf005e40e2b6a31bf86dcd036d":{
      "scriptId":"u63"},
    "194eff0cc0e949cb8a524c8ca4832d8c":{
      "scriptId":"u64"},
    "11ece367f0594dd9b148950057d101fd":{
      "scriptId":"u65"},
    "736d38f3d6cb4a01b708170d1e81fa48":{
      "scriptId":"u66"},
    "a5dcc6f728bf4aeaa48aefccac9a307b":{
      "scriptId":"u67"},
    "1f49b7e467004911bb577101f33c8fdd":{
      "scriptId":"u68"},
    "71e29acd117241fda7392fd1ad07b15d":{
      "scriptId":"u69"},
    "0f03f0f1bb0c4d618d4085c5c943a5c1":{
      "scriptId":"u70"},
    "9d0c9958794641869705c945a15c9bc7":{
      "scriptId":"u71"},
    "20eca1d11f844379a30e1837f4cc3ea8":{
      "scriptId":"u72"},
    "41a87b0fd7f6435eae933fc27e085137":{
      "scriptId":"u73"},
    "d275f1fcc902457286c14146f6d26577":{
      "scriptId":"u74"},
    "d8a925c63fe8439e8283e5cd3453d3b2":{
      "scriptId":"u75"},
    "f10ab4cbbbbb49beb5b231182869171c":{
      "scriptId":"u76"},
    "43c08cdaaa6a47dd885992d7dcb3df08":{
      "scriptId":"u77"},
    "190ff44652a7414aa713cfef8c3b7bc6":{
      "scriptId":"u78",
      "03bd36ac64d041918c6dc3aa6374751a":{
        "scriptId":"u79"},
      "df66acca03bf499aa135bbcb6227b967":{
        "scriptId":"u80"},
      "6b692c7b87a3402b9ce9a61959969a10":{
        "scriptId":"u81"},
      "8c6cdd631e4d43428f7d756760855ef4":{
        "scriptId":"u82"},
      "ff8b4a4f418f41888cc0cac89e0b6cc6":{
        "scriptId":"u83"},
      "95d3026929da487595c46ec0c6ac3c87":{
        "scriptId":"u84"},
      "7afee1299b2b48a8a6be957ef89fe2af":{
        "scriptId":"u85"},
      "cc8fa126bf8e4cc6a842e757b7b28f3f":{
        "scriptId":"u86"},
      "b796130b619e4ad2b19a50e713cbbd40":{
        "scriptId":"u87"},
      "6b0b3db928fd4bdc8935f7e7b7748902":{
        "scriptId":"u88"},
      "ef5b7a53388f4425b08610aa93a79189":{
        "scriptId":"u89"},
      "5d9fbdea8ac94145a0e1dac4db9bfff5":{
        "scriptId":"u90"},
      "a13a6ce77356497b9dcac880c9acd548":{
        "scriptId":"u91"},
      "4416e82b29c84e7cb040527f4c8a5b03":{
        "scriptId":"u92"},
      "01bcdd63c23f4cdd8d8a524437ac1102":{
        "scriptId":"u93"},
      "82d50f80e0ba46fc820d9a4ca86db1f1":{
        "scriptId":"u94"},
      "eabd7026a24944e1a21cd8e4f0df4689":{
        "scriptId":"u95"},
      "7cd7f6c343744aaf975767f39e9ee417":{
        "scriptId":"u96"}},
    "db50a5edca0a42b190687019a2219cd5":{
      "scriptId":"u97"},
    "9b087f52680048538f4754f1d49e1d12":{
      "scriptId":"u98"},
    "fa4f68dba7704716893e8bf0b28f5b39":{
      "scriptId":"u99"},
    "73fb2b1427f54240baeedd5731eec96f":{
      "scriptId":"u100"},
    "05975030f9834e44a9cc82b69aa00f35":{
      "scriptId":"u101"},
    "c2536826e7c64da09e59f52b9d3c443c":{
      "scriptId":"u102"}}});