$axure.loadCurrentPage({
  "url":"功能组信息.html",
  "generationDate":new Date(1488533173399.42),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e9215812802c4985981a3a8f0a8c56f3",
    "type":"Axure:Page",
    "name":"功能组信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"10cd476a88164e658ef0721e299f485d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":0}},
          "adaptiveStyles":{
},
          "masterId":"7a02efa0d5604338a3be75f38bcf2b86"},
{
          "id":"b3334f280ed74b7db01ad66d3840ee39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":87},
            "size":{
              "width":242,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc2e17110c67471b8644c91e514cad0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":358,
                  "y":87},
                "size":{
                  "width":242,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ddaa7006c2b94cd9a39c784e8e0106bf",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":351,
              "y":262},
            "size":{
              "width":739,
              "height":126}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eee9fa9ef764d6a9c4e8b9a7a6ddcc5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":36},
                "size":{
                  "width":128,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"78c6092e79ff40bd8ab8c19923cd5a5a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":36},
                    "size":{
                      "width":128,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u37.png"}},
{
              "id":"77db098c0b684a1a9811b5eb7f926bc9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":66},
                "size":{
                  "width":128,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a2157233fc494736b2c029a2b17589c4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":66},
                    "size":{
                      "width":128,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u37.png"}},
{
              "id":"61086198b2674d168b1a5d07696e2692",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":579,
                  "y":36},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ec4c1da7121474fb87d3063c294263d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":579,
                      "y":36},
                    "size":{
                      "width":160,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u36.png"}},
{
              "id":"5ac1b789633c4f41b26a62dc34256726",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":579,
                  "y":66},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2d19595316574819a0d28465a03f328a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":579,
                      "y":66},
                    "size":{
                      "width":160,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u36.png"}},
{
              "id":"abcb761091a74bbdb25cdc1a6c14b214",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":348,
                  "y":36},
                "size":{
                  "width":231,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"724f2a987e594564b21bfbe0c13f7507",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":348,
                      "y":36},
                    "size":{
                      "width":231,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u34.png"}},
{
              "id":"69d01eda85894777bb72348550ee7853",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":348,
                  "y":66},
                "size":{
                  "width":231,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a20928e8f07a4d2f87c3a7e303e5d5cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":348,
                      "y":66},
                    "size":{
                      "width":231,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u34.png"}},
{
              "id":"92df1b0b9b3d4f4f818941f936553892",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "size":{
                  "width":128,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c75854a253b4bb8a6faac38a39af757",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "size":{
                      "width":128,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u25.png"}},
{
              "id":"1b20b2e177e34452ae0abec8e842e3cf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":348,
                  "y":0},
                "size":{
                  "width":231,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e3a555edd62147e199e98666fd1e4dd5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":348,
                      "y":0},
                    "size":{
                      "width":231,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u26.png"}},
{
              "id":"7f646f146817448daeef029c6b09d79c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":579,
                  "y":0},
                "size":{
                  "width":160,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ebf26866fa94a5ea26c8255c96c0cde",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":579,
                      "y":0},
                    "size":{
                      "width":160,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u28.png"}},
{
              "id":"508e746110f4423c82d59c7f17f10e3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":96},
                "size":{
                  "width":128,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f7e674c9102e4e4594da13527f64e7cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":96},
                    "size":{
                      "width":128,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/申请功能分组申请/u61.png"}},
{
              "id":"bd28eec9fc784988ade9e14e9186c98e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":348,
                  "y":96},
                "size":{
                  "width":231,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"303c8fa8a3334751941d7bfa8d8a4a49",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":348,
                      "y":96},
                    "size":{
                      "width":231,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u50.png"}},
{
              "id":"61f505021fd44918a4726c8e01e8de66",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":579,
                  "y":96},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dbe3e953181f48edb50804cb9b1ea9bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":579,
                      "y":96},
                    "size":{
                      "width":160,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/首页/u7.png"}},
{
              "id":"ed647e6daf5a41b1bcbed51ca69a1274",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":128,
                  "y":0},
                "size":{
                  "width":220,
                  "height":36}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"decdedf1924445c1b833a8e986f216dd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "location":{
                      "x":128,
                      "y":0},
                    "size":{
                      "width":220,
                      "height":36}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u24.png"}},
{
              "id":"0ce9fa30f0ee4d8b8cfa540ac241da91",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":36},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a02c57b7f5fe410c8e1177dcb06ac48e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":128,
                      "y":36},
                    "size":{
                      "width":220,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u32.png"}},
{
              "id":"2c02739cb5ad4670bb5f8e8eead4e057",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":66},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ad54d6b807a4b81af3f4635c1b94175",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":128,
                      "y":66},
                    "size":{
                      "width":220,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u32.png"}},
{
              "id":"e5b2e8917a6e4d62a03b508df6a236ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":128,
                  "y":96},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"88b3f8fca00842bbbedf4d55c2e196cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "location":{
                      "x":128,
                      "y":96},
                    "size":{
                      "width":220,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/功能组信息/u48.png"}}]},
{
          "id":"ad4bbe1f8a0540f392d2a567ef76f97d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":441},
            "size":{
              "width":340,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"568fe5ed54ef4fa1a23e68a54edfbec4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":441},
                "size":{
                  "width":340,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u82.png"}},
{
          "id":"33a55682789f46d9a6ba03b1a86213ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":422},
            "size":{
              "width":340,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"334c6fc7d4574b6b8fd8debbcda98e7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":370,
                  "y":422},
                "size":{
                  "width":340,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u84.png"}},
{
          "id":"8a5618c9c03244058e04934ad80114bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":482},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c31dd06a95fe40529a0bac247f219c2b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":482},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27269c0af6d6432aaba3eec4c9d37d20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":473},
            "size":{
              "width":70,
              "height":40},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF009900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ce77bd66e774a389c50f69691e5aaeb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":470,
                  "y":473},
                "size":{
                  "width":70,
                  "height":40},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF009900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/api提供者认证审核/u88.png"}},
{
          "id":"f403f90f78a64b97bd971593cb697ee7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":473},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6303c2606004255a458946fea56675b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":565,
                  "y":473},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u88.png"}},
{
          "id":"2f7a1401638049198f9bf62b00432d8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":394,
              "y":534},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e96a658aedad4c6c9b4640c565b12d8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":394,
                  "y":534},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e922263dcb104adaad68558242f44625",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":530},
            "size":{
              "width":220,
              "height":62}},
          "adaptiveStyles":{
}},
{
          "id":"d01ab829ec584df9bc0c4cd3d3851b75",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":622},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"260d072e844f43da9c4d8dc355ea314d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":565,
              "y":622},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f451e359b6a040f9966927c733605452",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":140,
              "y":204},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34db475a483f4a15b492d17827e7e0e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":140,
                  "y":204},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 申请功能分组申请",
                      "target":{
                        "targetType":"page",
                        "url":"申请功能分组申请.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/开发者认证审核/u19.png"}},
{
          "id":"52eadc79a3334de797c7032abb0be44e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":904,
              "y":546},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6b6da7e4bd248959d1ebc322c6f57ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":904,
                  "y":546},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5883889dec36442c8968ea2c56a2f224",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":441},
            "size":{
              "width":340,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2133a232362548dcb690a8eeaf04ceb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":441},
                "size":{
                  "width":340,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u82.png"}},
{
          "id":"0378e547d8d94a148773b5f9fd8fe62e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":740,
              "y":422},
            "size":{
              "width":340,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d225c7f1dc749409766c7f94af7eb3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":740,
                  "y":422},
                "size":{
                  "width":340,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/开发者认证审核/u84.png"}},
{
          "id":"2f22c278b0d049bda8c20bde18e7d75d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":764,
              "y":482},
            "size":{
              "width":246,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e52a1e6672df4e1e82d51657e7c7cbc4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":764,
                  "y":482},
                "size":{
                  "width":246,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f81c7a355ceb49cb9c21a6d55f83f822",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":860,
              "y":571},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "7a02efa0d5604338a3be75f38bcf2b86":{
      "packageId":"7a02efa0d5604338a3be75f38bcf2b86",
      "type":"Axure:Master",
      "name":"新母版 1",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"03bd36ac64d041918c6dc3aa6374751a",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":1000,
                "height":60}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df66acca03bf499aa135bbcb6227b967",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1000,
                    "height":60}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u1.png"}},
{
            "id":"6b692c7b87a3402b9ce9a61959969a10",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"20px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF0099FF,
                "opacity":1},
              "location":{
                "x":59,
                "y":18},
              "size":{
                "width":241,
                "height":24}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8c6cdd631e4d43428f7d756760855ef4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"20px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF0099FF,
                    "opacity":1},
                  "location":{
                    "x":59,
                    "y":18},
                  "size":{
                    "width":241,
                    "height":24}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ff8b4a4f418f41888cc0cac89e0b6cc6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":59},
              "size":{
                "width":200,
                "height":421}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"95d3026929da487595c46ec0c6ac3c87",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":0,
                    "y":59},
                  "size":{
                    "width":200,
                    "height":421}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页/u5.png"}},
{
            "id":"7afee1299b2b48a8a6be957ef89fe2af",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":59},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cc8fa126bf8e4cc6a842e757b7b28f3f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":59},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API提供者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"api提供者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"b796130b619e4ad2b19a50e713cbbd40",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":88},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6b0b3db928fd4bdc8935f7e7b7748902",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":88},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 开发者认证审核",
                        "target":{
                          "targetType":"page",
                          "url":"开发者认证审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"ef5b7a53388f4425b08610aa93a79189",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":175},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5d9fbdea8ac94145a0e1dac4db9bfff5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":175},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 应用上线审核",
                        "target":{
                          "targetType":"page",
                          "url":"应用上线审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"a13a6ce77356497b9dcac880c9acd548",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":117},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4416e82b29c84e7cb040527f4c8a5b03",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":117},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 API接口审核",
                        "target":{
                          "targetType":"page",
                          "url":"api接口审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"01bcdd63c23f4cdd8d8a524437ac1102",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":146},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82d50f80e0ba46fc820d9a4ca86db1f1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":146},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 接入指南审核",
                        "target":{
                          "targetType":"page",
                          "url":"接入指南审核.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}},
{
            "id":"eabd7026a24944e1a21cd8e4f0df4689",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "location":{
                "x":40,
                "y":204},
              "size":{
                "width":160,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7cd7f6c343744aaf975767f39e9ee417",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":40,
                    "y":204},
                  "size":{
                    "width":160,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 申请功能分组申请",
                        "target":{
                          "targetType":"page",
                          "url":"申请功能分组申请.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/首页/u7.png"}}]}}},
  "objectPaths":{
    "10cd476a88164e658ef0721e299f485d":{
      "scriptId":"u0",
      "03bd36ac64d041918c6dc3aa6374751a":{
        "scriptId":"u1"},
      "df66acca03bf499aa135bbcb6227b967":{
        "scriptId":"u2"},
      "6b692c7b87a3402b9ce9a61959969a10":{
        "scriptId":"u3"},
      "8c6cdd631e4d43428f7d756760855ef4":{
        "scriptId":"u4"},
      "ff8b4a4f418f41888cc0cac89e0b6cc6":{
        "scriptId":"u5"},
      "95d3026929da487595c46ec0c6ac3c87":{
        "scriptId":"u6"},
      "7afee1299b2b48a8a6be957ef89fe2af":{
        "scriptId":"u7"},
      "cc8fa126bf8e4cc6a842e757b7b28f3f":{
        "scriptId":"u8"},
      "b796130b619e4ad2b19a50e713cbbd40":{
        "scriptId":"u9"},
      "6b0b3db928fd4bdc8935f7e7b7748902":{
        "scriptId":"u10"},
      "ef5b7a53388f4425b08610aa93a79189":{
        "scriptId":"u11"},
      "5d9fbdea8ac94145a0e1dac4db9bfff5":{
        "scriptId":"u12"},
      "a13a6ce77356497b9dcac880c9acd548":{
        "scriptId":"u13"},
      "4416e82b29c84e7cb040527f4c8a5b03":{
        "scriptId":"u14"},
      "01bcdd63c23f4cdd8d8a524437ac1102":{
        "scriptId":"u15"},
      "82d50f80e0ba46fc820d9a4ca86db1f1":{
        "scriptId":"u16"},
      "eabd7026a24944e1a21cd8e4f0df4689":{
        "scriptId":"u17"},
      "7cd7f6c343744aaf975767f39e9ee417":{
        "scriptId":"u18"}},
    "b3334f280ed74b7db01ad66d3840ee39":{
      "scriptId":"u19"},
    "fc2e17110c67471b8644c91e514cad0f":{
      "scriptId":"u20"},
    "ddaa7006c2b94cd9a39c784e8e0106bf":{
      "scriptId":"u21"},
    "92df1b0b9b3d4f4f818941f936553892":{
      "scriptId":"u22"},
    "1c75854a253b4bb8a6faac38a39af757":{
      "scriptId":"u23"},
    "ed647e6daf5a41b1bcbed51ca69a1274":{
      "scriptId":"u24"},
    "decdedf1924445c1b833a8e986f216dd":{
      "scriptId":"u25"},
    "1b20b2e177e34452ae0abec8e842e3cf":{
      "scriptId":"u26"},
    "e3a555edd62147e199e98666fd1e4dd5":{
      "scriptId":"u27"},
    "7f646f146817448daeef029c6b09d79c":{
      "scriptId":"u28"},
    "6ebf26866fa94a5ea26c8255c96c0cde":{
      "scriptId":"u29"},
    "4eee9fa9ef764d6a9c4e8b9a7a6ddcc5":{
      "scriptId":"u30"},
    "78c6092e79ff40bd8ab8c19923cd5a5a":{
      "scriptId":"u31"},
    "0ce9fa30f0ee4d8b8cfa540ac241da91":{
      "scriptId":"u32"},
    "a02c57b7f5fe410c8e1177dcb06ac48e":{
      "scriptId":"u33"},
    "abcb761091a74bbdb25cdc1a6c14b214":{
      "scriptId":"u34"},
    "724f2a987e594564b21bfbe0c13f7507":{
      "scriptId":"u35"},
    "61086198b2674d168b1a5d07696e2692":{
      "scriptId":"u36"},
    "2ec4c1da7121474fb87d3063c294263d":{
      "scriptId":"u37"},
    "77db098c0b684a1a9811b5eb7f926bc9":{
      "scriptId":"u38"},
    "a2157233fc494736b2c029a2b17589c4":{
      "scriptId":"u39"},
    "2c02739cb5ad4670bb5f8e8eead4e057":{
      "scriptId":"u40"},
    "0ad54d6b807a4b81af3f4635c1b94175":{
      "scriptId":"u41"},
    "69d01eda85894777bb72348550ee7853":{
      "scriptId":"u42"},
    "a20928e8f07a4d2f87c3a7e303e5d5cb":{
      "scriptId":"u43"},
    "5ac1b789633c4f41b26a62dc34256726":{
      "scriptId":"u44"},
    "2d19595316574819a0d28465a03f328a":{
      "scriptId":"u45"},
    "508e746110f4423c82d59c7f17f10e3b":{
      "scriptId":"u46"},
    "f7e674c9102e4e4594da13527f64e7cb":{
      "scriptId":"u47"},
    "e5b2e8917a6e4d62a03b508df6a236ea":{
      "scriptId":"u48"},
    "88b3f8fca00842bbbedf4d55c2e196cb":{
      "scriptId":"u49"},
    "bd28eec9fc784988ade9e14e9186c98e":{
      "scriptId":"u50"},
    "303c8fa8a3334751941d7bfa8d8a4a49":{
      "scriptId":"u51"},
    "61f505021fd44918a4726c8e01e8de66":{
      "scriptId":"u52"},
    "dbe3e953181f48edb50804cb9b1ea9bf":{
      "scriptId":"u53"},
    "ad4bbe1f8a0540f392d2a567ef76f97d":{
      "scriptId":"u54"},
    "568fe5ed54ef4fa1a23e68a54edfbec4":{
      "scriptId":"u55"},
    "33a55682789f46d9a6ba03b1a86213ab":{
      "scriptId":"u56"},
    "334c6fc7d4574b6b8fd8debbcda98e7b":{
      "scriptId":"u57"},
    "8a5618c9c03244058e04934ad80114bf":{
      "scriptId":"u58"},
    "c31dd06a95fe40529a0bac247f219c2b":{
      "scriptId":"u59"},
    "27269c0af6d6432aaba3eec4c9d37d20":{
      "scriptId":"u60"},
    "8ce77bd66e774a389c50f69691e5aaeb":{
      "scriptId":"u61"},
    "f403f90f78a64b97bd971593cb697ee7":{
      "scriptId":"u62"},
    "f6303c2606004255a458946fea56675b":{
      "scriptId":"u63"},
    "2f7a1401638049198f9bf62b00432d8f":{
      "scriptId":"u64"},
    "e96a658aedad4c6c9b4640c565b12d8d":{
      "scriptId":"u65"},
    "e922263dcb104adaad68558242f44625":{
      "scriptId":"u66"},
    "d01ab829ec584df9bc0c4cd3d3851b75":{
      "scriptId":"u67"},
    "260d072e844f43da9c4d8dc355ea314d":{
      "scriptId":"u68"},
    "f451e359b6a040f9966927c733605452":{
      "scriptId":"u69"},
    "34db475a483f4a15b492d17827e7e0e9":{
      "scriptId":"u70"},
    "52eadc79a3334de797c7032abb0be44e":{
      "scriptId":"u71"},
    "d6b6da7e4bd248959d1ebc322c6f57ed":{
      "scriptId":"u72"},
    "5883889dec36442c8968ea2c56a2f224":{
      "scriptId":"u73"},
    "2133a232362548dcb690a8eeaf04ceb7":{
      "scriptId":"u74"},
    "0378e547d8d94a148773b5f9fd8fe62e":{
      "scriptId":"u75"},
    "2d225c7f1dc749409766c7f94af7eb3e":{
      "scriptId":"u76"},
    "2f22c278b0d049bda8c20bde18e7d75d":{
      "scriptId":"u77"},
    "e52a1e6672df4e1e82d51657e7c7cbc4":{
      "scriptId":"u78"},
    "f81c7a355ceb49cb9c21a6d55f83f822":{
      "scriptId":"u79"}}});